"""GBrain memory provider plugin — hardcoded tool schemas.

Connects to GBrain via MCP-over-HTTP (StreamableHTTP) and exposes
83 hardcoded tool schemas through the MemoryProvider interface.
No dynamic discovery — schemas are generated from the live server
and stored in _schemas.py. Regenerate with:

    python3 -c "from _schemas import *; ..."

Config source (priority):
  1. Env vars: MCP_GBRAIN_URL, MCP_GBRAIN_API_KEY
  2. Env vars: GBRAIN_MCP_URL, GBRAIN_API_TOKEN, GBRAIN_MCP_TOKEN
  3. $HERMES_HOME/gbrain_memory.json
"""

from __future__ import annotations

import json
import logging
import os
import re
import threading
from datetime import date
from pathlib import Path
from typing import Any

import httpx

from agent.memory_provider import MemoryProvider
from hermes_constants import get_hermes_home

from ._schemas import HARDCODED_SCHEMAS, HARDCODED_SCHEMA_DICTS

logger = logging.getLogger(__name__)

_DEFAULT_URL = "https://gbrain.plainrandom.com/mcp"
_DEFAULT_TIMEOUT = 30


class _McpError(RuntimeError):
    pass


class _McpClient:
    """Thread-safe MCP-over-HTTP client. Connects on-demand, no tool discovery."""

    def __init__(self, url: str, api_token: str, timeout: float = _DEFAULT_TIMEOUT):
        self._base_url = url.rstrip("/")
        self._api_token = api_token
        self._timeout = timeout
        self._session_id: str | None = None
        self._lock = threading.RLock()
        self._closed = False
        self._req_id = 0

    def call(self, tool_name: str, arguments: dict) -> dict:
        if self._closed:
            raise _McpError("Client is closed")
        with self._lock:
            self._ensure_session()
            body = {
                "jsonrpc": "2.0",
                "id": self._next_id(),
                "method": "tools/call",
                "params": {"name": tool_name, "arguments": arguments or {}},
            }
            headers = self._auth_headers()
        try:
            resp = httpx.post(self._base_url, json=body, headers=headers, timeout=self._timeout)
            resp.raise_for_status()
            result = self._parse_sse(resp.text)
        except (httpx.HTTPStatusError, httpx.TimeoutException, httpx.ConnectError) as exc:
            logger.debug("MCP call failed, reconnecting: %s", exc)
            with self._lock:
                self._session_id = None
                self._ensure_session()
                body["id"] = self._next_id()
                headers = self._auth_headers()
            retry_resp = httpx.post(self._base_url, json=body, headers=headers, timeout=self._timeout)
            retry_resp.raise_for_status()
            result = self._parse_sse(retry_resp.text)
        error = result.get("error")
        if error:
            raise _McpError(error.get("message", str(error)))
        r = result.get("result", {})
        if r.get("isError"):
            content = r.get("content", [])
            msg = content[0].get("text", "Unknown error") if content else "Unknown error"
            raise _McpError(msg)
        return r

    def close(self):
        with self._lock:
            self._closed = True
            self._session_id = None

    def _auth_headers(self) -> dict:
        h = {"Content-Type": "application/json", "Accept": "application/json, text/event-stream"}
        if self._api_token:
            h["Authorization"] = f"Bearer {self._api_token}"
        if self._session_id:
            h["Mcp-Session-Id"] = self._session_id
        return h

    def _next_id(self) -> int:
        self._req_id += 1
        return self._req_id

    @staticmethod
    def _parse_sse(text: str) -> dict:
        last_result = None
        for line in text.splitlines():
            stripped = line.strip()
            if stripped.startswith("data: "):
                try:
                    last_result = json.loads(stripped[6:])
                except json.JSONDecodeError:
                    continue
        if last_result is not None:
            return last_result
        return json.loads(text)

    def _ensure_session(self):
        if self._session_id is not None:
            return
        with self._lock:
            if self._session_id is not None:
                return
            resp = httpx.post(
                self._base_url,
                json={
                    "jsonrpc": "2.0",
                    "id": self._next_id(),
                    "method": "initialize",
                    "params": {
                        "protocolVersion": "2025-03-26",
                        "capabilities": {},
                        "clientInfo": {"name": "hermes-gbrain", "version": "1.0.0"},
                    },
                },
                headers=self._auth_headers(),
                timeout=self._timeout,
            )
            resp.raise_for_status()
            sid = resp.headers.get("mcp-session-id") or resp.headers.get("Mcp-Session-Id")
            if sid:
                self._session_id = str(sid)
            try:
                httpx.post(
                    self._base_url,
                    json={"jsonrpc": "2.0", "method": "notifications/initialized"},
                    headers=self._auth_headers(),
                    timeout=5,
                )
            except Exception:
                pass


def _load_config() -> dict:
    hermes_home = get_hermes_home()
    config_path = Path(hermes_home) / "gbrain_memory.json"
    config = {}
    if config_path.exists():
        try:
            config = json.loads(config_path.read_text())
        except (json.JSONDecodeError, OSError) as e:
            logger.warning("Failed to read %s: %s", config_path, e)
    config["url"] = (
        os.environ.get("MCP_GBRAIN_URL")
        or os.environ.get("GBRAIN_MCP_URL")
        or config.get("url", _DEFAULT_URL)
    )
    config["api_token"] = (
        os.environ.get("MCP_GBRAIN_API_KEY")
        or os.environ.get("GBRAIN_API_TOKEN")
        or os.environ.get("GBRAIN_MCP_TOKEN")
        or config.get("api_token", "")
    )
    config["timeout"] = float(
        os.environ.get("GBRAIN_MCP_TIMEOUT") or config.get("timeout", _DEFAULT_TIMEOUT)
    )
    return config


class GBrainMemoryProvider(MemoryProvider):

    def __init__(self):
        self._config: dict = {}
        self._mcp: _McpClient | None = None

    # ── brain-agent-loop helpers ──────────────────────────────────────

    # ── Mask of words that are DEFINITELY NOT entities ────────────────
    # Assumption: all words are potential entities. Strip out the closed
    # class of words that can't be entities (articles, pronouns, prepositions,
    # conjunctions, auxiliary verbs, common verbs/adjectives/adverbs,
    # greetings, discourse markers, time words, number words, etc.).
    # Everything else passes through to the brain — if it's not a known
    # entity, the search returns nothing (wasted 200ms, nothing more).
    # 2,226 words total.
    _STOP_WORDS = frozenset({
        "a",
        "able",
        "aboard",
        "about",
        "above",
        "absolute",
        "absolutely",
        "accept",
        "acceptable",
        "accepted",
        "accepting",
        "accepts",
        "across",
        "actual",
        "actually",
        "add",
        "added",
        "adding",
        "additional",
        "address",
        "adds",
        "afraid",
        "after",
        "afternoon",
        "against",
        "age",
        "ago",
        "agree",
        "agreed",
        "agreeing",
        "agrees",
        "ah",
        "aha",
        "ahem",
        "alas",
        "alive",
        "all",
        "allow",
        "allowed",
        "allowing",
        "allows",
        "almost",
        "alone",
        "along",
        "alongside",
        "already",
        "alright",
        "also",
        "alternative",
        "although",
        "always",
        "am",
        "amazing",
        "amid",
        "amidst",
        "among",
        "amongst",
        "an",
        "and",
        "angry",
        "annual",
        "annually",
        "another",
        "answer",
        "answered",
        "answering",
        "answers",
        "anxious",
        "any",
        "anybody",
        "anymore",
        "anyone",
        "anything",
        "anyway",
        "anywhere",
        "apparent",
        "apparently",
        "appr",
        "april",
        "are",
        "area",
        "aren't",
        "around",
        "as",
        "ask",
        "asked",
        "asking",
        "asks",
        "at",
        "ate",
        "aug",
        "august",
        "automatically",
        "autumn",
        "available",
        "aware",
        "away",
        "awesome",
        "awful",
        "aww",
        "back",
        "bad",
        "basic",
        "basically",
        "be",
        "beautiful",
        "became",
        "because",
        "become",
        "becomes",
        "becoming",
        "been",
        "before",
        "began",
        "begin",
        "beginning",
        "begins",
        "begun",
        "behind",
        "being",
        "believe",
        "believed",
        "believes",
        "believing",
        "below",
        "beneath",
        "beside",
        "besides",
        "better",
        "between",
        "beyond",
        "big",
        "billion",
        "birthday",
        "bit",
        "blank",
        "blind",
        "both",
        "bottom",
        "bought",
        "breakfast",
        "brief",
        "briefly",
        "bright",
        "brightly",
        "bring",
        "bringing",
        "brings",
        "broad",
        "broken",
        "brought",
        "build",
        "building",
        "builds",
        "built",
        "busy",
        "but",
        "buy",
        "buying",
        "buys",
        "by",
        "bye",
        "call",
        "called",
        "calling",
        "calls",
        "calm",
        "came",
        "can",
        "can't",
        "cannot",
        "capable",
        "careful",
        "carried",
        "carries",
        "carry",
        "carrying",
        "case",
        "catch",
        "catches",
        "catching",
        "category",
        "caught",
        "cause",
        "century",
        "certain",
        "certainly",
        "chance",
        "change",
        "changed",
        "changes",
        "changing",
        "chat",
        "chats",
        "chatted",
        "chatting",
        "cheap",
        "check",
        "checked",
        "checking",
        "checks",
        "cheerful",
        "cheers",
        "choice",
        "choose",
        "chooses",
        "choosing",
        "chose",
        "chosen",
        "circa",
        "clean",
        "clear",
        "clearly",
        "clever",
        "close",
        "closely",
        "cold",
        "come",
        "comes",
        "comfortable",
        "coming",
        "common",
        "complete",
        "completely",
        "complex",
        "concerned",
        "concerning",
        "condition",
        "confident",
        "confused",
        "connection",
        "conscious",
        "consequence",
        "consider",
        "considered",
        "considering",
        "considers",
        "constant",
        "constantly",
        "content",
        "context",
        "continually",
        "continue",
        "continued",
        "continues",
        "continuing",
        "control",
        "cool",
        "correct",
        "cost",
        "could",
        "could've",
        "couldn't",
        "crazy",
        "create",
        "created",
        "creates",
        "creating",
        "creative",
        "curious",
        "current",
        "currently",
        "cut",
        "cuts",
        "cutting",
        "daily",
        "dangerous",
        "dare",
        "daren't",
        "dark",
        "data",
        "dawn",
        "day",
        "dead",
        "deal",
        "dear",
        "dec",
        "decade",
        "december",
        "decide",
        "decided",
        "decides",
        "deciding",
        "deep",
        "deeply",
        "definite",
        "definitely",
        "depth",
        "description",
        "despite",
        "detail",
        "develop",
        "developed",
        "developing",
        "develops",
        "did",
        "didn't",
        "die",
        "died",
        "dies",
        "difference",
        "different",
        "difficult",
        "dinner",
        "direct",
        "direction",
        "directly",
        "dirty",
        "distance",
        "distant",
        "distinct",
        "distributed",
        "distribution",
        "do",
        "does",
        "doesn't",
        "doing",
        "don't",
        "double",
        "doubtful",
        "doubtfully",
        "down",
        "dozen",
        "draw",
        "drawing",
        "drawn",
        "draws",
        "drew",
        "drive",
        "driven",
        "drives",
        "driving",
        "drove",
        "due",
        "dull",
        "during",
        "dusk",
        "dying",
        "dynamic",
        "each",
        "eager",
        "early",
        "easily",
        "easy",
        "eat",
        "eaten",
        "eating",
        "eats",
        "edge",
        "effect",
        "effective",
        "effectively",
        "efficient",
        "effort",
        "eight",
        "eighteen",
        "eighth",
        "eighty",
        "either",
        "elderly",
        "elegant",
        "eleven",
        "eligible",
        "else",
        "elsewhere",
        "emotional",
        "empty",
        "end",
        "endless",
        "energetic",
        "enormously",
        "enough",
        "entire",
        "entirely",
        "equal",
        "error",
        "especially",
        "essential",
        "essentially",
        "even",
        "evening",
        "evenly",
        "eventual",
        "eventually",
        "ever",
        "every",
        "everybody",
        "everyone",
        "everything",
        "evident",
        "exact",
        "exactly",
        "example",
        "excellent",
        "except",
        "exception",
        "exceptional",
        "excited",
        "excluding",
        "exclusive",
        "exclusively",
        "excuse",
        "existence",
        "existing",
        "expect",
        "expected",
        "expecting",
        "expects",
        "experience",
        "explain",
        "explained",
        "explaining",
        "explains",
        "explicit",
        "extensive",
        "extensively",
        "extent",
        "external",
        "extra",
        "extreme",
        "extremely",
        "fact",
        "factor",
        "failure",
        "fair",
        "fairly",
        "faith",
        "fall",
        "fallen",
        "falling",
        "falls",
        "false",
        "familiar",
        "famous",
        "fancy",
        "far",
        "farewell",
        "fast",
        "fat",
        "fatal",
        "favorite",
        "feature",
        "feb",
        "february",
        "feel",
        "feeling",
        "feels",
        "fell",
        "felt",
        "few",
        "field",
        "fifteen",
        "fifth",
        "fifty",
        "figure",
        "fill",
        "filled",
        "filling",
        "fills",
        "final",
        "finally",
        "financial",
        "find",
        "finding",
        "finds",
        "fine",
        "finish",
        "finished",
        "finishes",
        "finishing",
        "firm",
        "firmly",
        "first",
        "five",
        "flat",
        "flexible",
        "focus",
        "follow",
        "followed",
        "following",
        "follows",
        "fond",
        "foolish",
        "for",
        "foreign",
        "forever",
        "forget",
        "forgets",
        "forgetting",
        "forgot",
        "forgotten",
        "form",
        "formal",
        "formally",
        "format",
        "former",
        "formerly",
        "fortnight",
        "forty",
        "found",
        "four",
        "fourteen",
        "fourth",
        "freedom",
        "frequent",
        "frequently",
        "fresh",
        "fri",
        "friday",
        "friendly",
        "from",
        "front",
        "full",
        "fully",
        "fun",
        "function",
        "fund",
        "funny",
        "further",
        "future",
        "gap",
        "general",
        "generally",
        "generous",
        "gentle",
        "gently",
        "genuine",
        "get",
        "gets",
        "getting",
        "giant",
        "give",
        "given",
        "gives",
        "giving",
        "glad",
        "gladly",
        "global",
        "go",
        "goal",
        "goes",
        "golden",
        "gone",
        "good",
        "goodbye",
        "goodnight",
        "got",
        "gotten",
        "gradual",
        "gradually",
        "grand",
        "grateful",
        "great",
        "greatly",
        "greetings",
        "ground",
        "grow",
        "growing",
        "grown",
        "grows",
        "growth",
        "ha",
        "had",
        "haha",
        "half",
        "hand",
        "happen",
        "happened",
        "happening",
        "happens",
        "happy",
        "hard",
        "hardly",
        "harsh",
        "has",
        "hasn't",
        "have",
        "haven't",
        "having",
        "he",
        "he'll",
        "he's",
        "head",
        "health",
        "healthy",
        "hear",
        "heard",
        "hearing",
        "hears",
        "heavily",
        "heavy",
        "height",
        "held",
        "hello",
        "help",
        "helped",
        "helpful",
        "helping",
        "helps",
        "her",
        "here",
        "here's",
        "hers",
        "herself",
        "hey",
        "hi",
        "hidden",
        "high",
        "highly",
        "him",
        "himself",
        "his",
        "hmm",
        "hold",
        "holding",
        "holds",
        "holiday",
        "home",
        "honest",
        "honestly",
        "hope",
        "hoped",
        "hopeful",
        "hopefully",
        "hopes",
        "hoping",
        "horrible",
        "hour",
        "how",
        "how's",
        "however",
        "huge",
        "huh",
        "human",
        "humble",
        "humorous",
        "hundred",
        "hungry",
        "i",
        "i'll",
        "i'm",
        "i've",
        "idea",
        "ideal",
        "identical",
        "if",
        "ill",
        "imagine",
        "imagined",
        "imagines",
        "imagining",
        "immediate",
        "immediately",
        "immense",
        "immensely",
        "impact",
        "importance",
        "important",
        "impossible",
        "impression",
        "impressive",
        "improve",
        "improved",
        "improvement",
        "improves",
        "improving",
        "in",
        "include",
        "included",
        "includes",
        "including",
        "income",
        "increase",
        "increased",
        "increases",
        "increasing",
        "indeed",
        "independent",
        "indicate",
        "indicates",
        "indicating",
        "indirectly",
        "individual",
        "inevitable",
        "inevitably",
        "infinite",
        "influence",
        "info",
        "information",
        "infrequently",
        "initial",
        "initially",
        "initiative",
        "inner",
        "innocent",
        "inside",
        "insight",
        "instance",
        "instantly",
        "instead",
        "intact",
        "intense",
        "intensely",
        "intentional",
        "intentionally",
        "interest",
        "interesting",
        "interestingly",
        "internal",
        "into",
        "introduction",
        "invisible",
        "involved",
        "inwardly",
        "is",
        "isn't",
        "isolated",
        "issue",
        "it",
        "it'll",
        "it's",
        "item",
        "its",
        "itself",
        "jan",
        "january",
        "job",
        "joint",
        "journey",
        "judgment",
        "jul",
        "july",
        "jun",
        "june",
        "junior",
        "just",
        "justice",
        "keen",
        "keep",
        "keeping",
        "keeps",
        "kept",
        "key",
        "kill",
        "killed",
        "killing",
        "kills",
        "kind",
        "know",
        "knowing",
        "known",
        "knows",
        "lack",
        "land",
        "large",
        "largely",
        "last",
        "late",
        "lately",
        "later",
        "latest",
        "latter",
        "law",
        "lay",
        "layer",
        "layout",
        "lazy",
        "lead",
        "leader",
        "leadership",
        "leading",
        "leads",
        "learn",
        "learned",
        "learning",
        "learns",
        "least",
        "leave",
        "leaves",
        "leaving",
        "led",
        "left",
        "legal",
        "legitimate",
        "less",
        "lesser",
        "lesson",
        "let",
        "let's",
        "lets",
        "letting",
        "level",
        "lie",
        "lies",
        "life",
        "light",
        "like",
        "liked",
        "likely",
        "likes",
        "liking",
        "limit",
        "limited",
        "line",
        "link",
        "list",
        "little",
        "live",
        "lived",
        "lives",
        "living",
        "load",
        "local",
        "logical",
        "lonely",
        "long",
        "look",
        "looked",
        "looking",
        "looks",
        "loose",
        "lose",
        "loses",
        "losing",
        "loss",
        "lost",
        "lot",
        "loud",
        "loudly",
        "love",
        "loved",
        "lovely",
        "loves",
        "loving",
        "low",
        "lower",
        "lucky",
        "lunch",
        "mad",
        "magnetic",
        "magnificent",
        "main",
        "mainly",
        "major",
        "make",
        "makes",
        "making",
        "manner",
        "many",
        "mar",
        "march",
        "mark",
        "marked",
        "marker",
        "marking",
        "marks",
        "mass",
        "massive",
        "match",
        "matter",
        "mature",
        "maximum",
        "may",
        "maybe",
        "me",
        "mean",
        "meaning",
        "means",
        "meant",
        "measure",
        "medium",
        "meet",
        "meeting",
        "meets",
        "member",
        "membership",
        "memory",
        "mental",
        "mention",
        "mere",
        "merely",
        "merry",
        "message",
        "met",
        "method",
        "midnight",
        "might",
        "might've",
        "mild",
        "mildly",
        "million",
        "mind",
        "mine",
        "minimum",
        "minor",
        "minus",
        "minute",
        "miss",
        "mistake",
        "mixed",
        "mixture",
        "mm",
        "mmhmm",
        "mmm",
        "mobile",
        "mode",
        "model",
        "moderate",
        "modern",
        "modest",
        "molecular",
        "moment",
        "mon",
        "monday",
        "month",
        "monthly",
        "mood",
        "moral",
        "more",
        "morning",
        "mortal",
        "most",
        "mostly",
        "motion",
        "motive",
        "move",
        "moved",
        "movement",
        "moves",
        "moving",
        "much",
        "multiple",
        "must",
        "must've",
        "mustn't",
        "mute",
        "mutual",
        "my",
        "myself",
        "mysterious",
        "nah",
        "name",
        "namely",
        "narrow",
        "nasty",
        "national",
        "native",
        "natural",
        "naturally",
        "nature",
        "naughty",
        "near",
        "nearby",
        "nearly",
        "neat",
        "necessarily",
        "necessary",
        "need",
        "needed",
        "needing",
        "needn't",
        "needs",
        "negative",
        "neither",
        "nervous",
        "net",
        "neutral",
        "never",
        "nevertheless",
        "new",
        "next",
        "nice",
        "nicely",
        "night",
        "nine",
        "nineteen",
        "ninety",
        "ninth",
        "no",
        "noble",
        "nobody",
        "noisy",
        "none",
        "noon",
        "nope",
        "nor",
        "normal",
        "normally",
        "not",
        "notable",
        "notably",
        "note",
        "noted",
        "notes",
        "nothing",
        "notice",
        "noticed",
        "notices",
        "noticing",
        "notion",
        "notorious",
        "notwithstanding",
        "nov",
        "novel",
        "november",
        "now",
        "nowadays",
        "nowhere",
        "nuclear",
        "numerous",
        "object",
        "objective",
        "observation",
        "obvious",
        "obviously",
        "occasional",
        "occasionally",
        "oct",
        "october",
        "odd",
        "of",
        "off",
        "offensive",
        "offer",
        "offered",
        "offering",
        "offers",
        "official",
        "officially",
        "often",
        "oh",
        "ok",
        "okay",
        "old",
        "on",
        "once",
        "one",
        "only",
        "onto",
        "ooh",
        "oops",
        "open",
        "opened",
        "opening",
        "openly",
        "opens",
        "opinion",
        "opposite",
        "option",
        "optional",
        "or",
        "order",
        "ordered",
        "ordering",
        "orders",
        "organic",
        "origin",
        "original",
        "originally",
        "other",
        "otherwise",
        "ouch",
        "ought",
        "our",
        "ours",
        "ourselves",
        "out",
        "outcome",
        "outer",
        "outgoing",
        "outstanding",
        "over",
        "overall",
        "overt",
        "overwhelming",
        "pace",
        "paid",
        "pair",
        "pale",
        "parallel",
        "part",
        "partial",
        "particular",
        "particularly",
        "partly",
        "partner",
        "parts",
        "party",
        "passage",
        "passing",
        "passion",
        "passionate",
        "passive",
        "past",
        "path",
        "patient",
        "pattern",
        "pause",
        "pay",
        "paying",
        "payment",
        "pays",
        "peaceful",
        "peculiar",
        "penalty",
        "pending",
        "people",
        "per",
        "perception",
        "perfectly",
        "perhaps",
        "period",
        "permanent",
        "permission",
        "person",
        "personal",
        "perspective",
        "persuasive",
        "pertinent",
        "phase",
        "phenomenon",
        "phew",
        "phone",
        "physical",
        "pick",
        "picked",
        "picking",
        "picks",
        "piece",
        "pilot",
        "pink",
        "place",
        "placed",
        "places",
        "placing",
        "plain",
        "plainly",
        "plan",
        "planned",
        "plausible",
        "play",
        "played",
        "playing",
        "plays",
        "pleasant",
        "please",
        "pleased",
        "pleasure",
        "plenty",
        "plus",
        "point",
        "pointed",
        "pointing",
        "points",
        "policy",
        "polite",
        "poor",
        "popular",
        "portable",
        "portion",
        "position",
        "positive",
        "possession",
        "possibility",
        "possible",
        "possibly",
        "potential",
        "power",
        "powerful",
        "practical",
        "practically",
        "practice",
        "precious",
        "precise",
        "precisely",
        "predictable",
        "prefer",
        "preference",
        "preferred",
        "preferring",
        "prefers",
        "pregnant",
        "preliminary",
        "premier",
        "premium",
        "preparation",
        "prepare",
        "prepared",
        "preposition",
        "presence",
        "present",
        "presentation",
        "presently",
        "preserve",
        "pressure",
        "pretty",
        "prevent",
        "preventing",
        "prevention",
        "previous",
        "previously",
        "price",
        "priceless",
        "primary",
        "prime",
        "primitive",
        "principal",
        "principle",
        "prior",
        "priority",
        "private",
        "probable",
        "probably",
        "problem",
        "procedure",
        "process",
        "produce",
        "produced",
        "produces",
        "producing",
        "product",
        "production",
        "productive",
        "professional",
        "profound",
        "progress",
        "progressive",
        "project",
        "prominent",
        "promise",
        "promising",
        "promotion",
        "prompt",
        "promptly",
        "proof",
        "proper",
        "properly",
        "property",
        "proposal",
        "propose",
        "proposed",
        "proposes",
        "proposing",
        "proposition",
        "prospect",
        "prospective",
        "protection",
        "protective",
        "proud",
        "prove",
        "proved",
        "proven",
        "proves",
        "provide",
        "provided",
        "provides",
        "providing",
        "proving",
        "provisional",
        "psychic",
        "public",
        "pull",
        "pulled",
        "pulling",
        "pulls",
        "purpose",
        "pursuit",
        "push",
        "pushed",
        "pushes",
        "pushing",
        "put",
        "puts",
        "putting",
        "puzzled",
        "qualified",
        "quality",
        "quantity",
        "quarter",
        "question",
        "quick",
        "quickly",
        "quiet",
        "quietly",
        "quite",
        "quote",
        "racial",
        "radical",
        "rainy",
        "raise",
        "raised",
        "raises",
        "raising",
        "random",
        "range",
        "rapid",
        "rare",
        "rarely",
        "rate",
        "rather",
        "ratio",
        "rational",
        "raw",
        "reach",
        "reached",
        "reaches",
        "reaching",
        "reaction",
        "read",
        "reading",
        "reads",
        "ready",
        "real",
        "realistic",
        "reality",
        "realize",
        "realized",
        "realizes",
        "realizing",
        "really",
        "reason",
        "reasonable",
        "reasonably",
        "receipt",
        "receive",
        "received",
        "receives",
        "receiving",
        "recent",
        "recently",
        "reception",
        "recipe",
        "recognition",
        "recognize",
        "recognized",
        "recognizes",
        "recognizing",
        "recommendation",
        "record",
        "recover",
        "recovery",
        "red",
        "reduced",
        "redundant",
        "refer",
        "reference",
        "referred",
        "referring",
        "refers",
        "reflection",
        "reform",
        "region",
        "register",
        "regret",
        "regular",
        "regularly",
        "relate",
        "related",
        "relates",
        "relating",
        "relation",
        "relationship",
        "relative",
        "relatively",
        "release",
        "released",
        "releases",
        "releasing",
        "relevance",
        "relevant",
        "reliable",
        "relief",
        "relieved",
        "religious",
        "reluctant",
        "reluctantly",
        "remain",
        "remained",
        "remaining",
        "remains",
        "remarkable",
        "remedy",
        "remember",
        "remembered",
        "remembering",
        "remembers",
        "reminder",
        "remote",
        "remove",
        "removed",
        "removes",
        "removing",
        "repeated",
        "repeatedly",
        "reported",
        "representative",
        "reproductive",
        "repulsive",
        "request",
        "require",
        "required",
        "requirement",
        "requires",
        "requiring",
        "research",
        "reservation",
        "reserve",
        "residence",
        "resident",
        "residual",
        "resignation",
        "resistant",
        "resolution",
        "resolve",
        "resource",
        "resources",
        "respect",
        "respectful",
        "respective",
        "respond",
        "responded",
        "responding",
        "responds",
        "response",
        "responsibility",
        "responsible",
        "rest",
        "restless",
        "restoration",
        "restricted",
        "restriction",
        "result",
        "resulted",
        "resulting",
        "results",
        "retail",
        "retention",
        "retired",
        "retirement",
        "return",
        "returned",
        "returning",
        "returns",
        "revelation",
        "revenue",
        "reverse",
        "review",
        "revised",
        "revolution",
        "reward",
        "rhythm",
        "rich",
        "right",
        "rigid",
        "ripe",
        "risk",
        "rival",
        "roger",
        "role",
        "room",
        "root",
        "rough",
        "roughly",
        "round",
        "route",
        "routine",
        "routinely",
        "royal",
        "rude",
        "rule",
        "ruling",
        "run",
        "running",
        "runs",
        "rural",
        "sacred",
        "sad",
        "sadly",
        "safe",
        "said",
        "sake",
        "salient",
        "same",
        "sample",
        "sat",
        "satisfied",
        "saturday",
        "save",
        "saved",
        "saves",
        "saving",
        "saw",
        "say",
        "saying",
        "says",
        "scale",
        "scarcely",
        "scared",
        "scene",
        "sceptical",
        "schedule",
        "scheme",
        "school",
        "science",
        "scope",
        "score",
        "search",
        "season",
        "seasonal",
        "seat",
        "second",
        "secondary",
        "secret",
        "secretly",
        "section",
        "sector",
        "secure",
        "security",
        "see",
        "seed",
        "seeing",
        "seek",
        "seeking",
        "seeks",
        "seem",
        "seemed",
        "seeming",
        "seemingly",
        "seems",
        "segment",
        "seldom",
        "select",
        "selection",
        "selective",
        "self",
        "send",
        "sending",
        "sends",
        "senior",
        "sense",
        "sensible",
        "sensitive",
        "sent",
        "separate",
        "separately",
        "sept",
        "september",
        "sequence",
        "series",
        "serious",
        "seriously",
        "service",
        "session",
        "set",
        "sets",
        "setting",
        "seven",
        "seventeen",
        "seventh",
        "seventy",
        "several",
        "severe",
        "severely",
        "shallow",
        "shape",
        "share",
        "sharp",
        "sharply",
        "she",
        "she'll",
        "she's",
        "sheer",
        "shelter",
        "shift",
        "shiny",
        "shock",
        "shocked",
        "shop",
        "short",
        "shortage",
        "shortly",
        "shot",
        "should",
        "should've",
        "shouldn't",
        "show",
        "showed",
        "showing",
        "shown",
        "shows",
        "shut",
        "shy",
        "sick",
        "side",
        "sight",
        "sign",
        "signal",
        "significance",
        "significant",
        "significantly",
        "silence",
        "silent",
        "silently",
        "silly",
        "similar",
        "similarly",
        "simple",
        "simply",
        "since",
        "single",
        "singular",
        "sir",
        "sit",
        "site",
        "sits",
        "sitting",
        "situation",
        "situational",
        "six",
        "sixteen",
        "sixth",
        "sixty",
        "size",
        "skill",
        "skilled",
        "sleepy",
        "slight",
        "slightly",
        "slim",
        "slow",
        "slowly",
        "small",
        "smart",
        "smooth",
        "smoothly",
        "so",
        "social",
        "society",
        "soft",
        "softly",
        "software",
        "soil",
        "solar",
        "sole",
        "solely",
        "solid",
        "solution",
        "solve",
        "solved",
        "solves",
        "solving",
        "some",
        "somebody",
        "somehow",
        "someone",
        "something",
        "sometimes",
        "somewhat",
        "somewhere",
        "soon",
        "sophisticated",
        "sorry",
        "sort",
        "sorted",
        "sorting",
        "sorts",
        "sound",
        "sour",
        "source",
        "space",
        "spare",
        "sparse",
        "speak",
        "speaking",
        "speaks",
        "special",
        "specific",
        "specifically",
        "spectacular",
        "speech",
        "speed",
        "speedy",
        "spend",
        "spending",
        "spends",
        "spent",
        "spirit",
        "spiritual",
        "splendid",
        "spoken",
        "spot",
        "spotless",
        "spread",
        "spring",
        "stable",
        "stage",
        "stale",
        "stand",
        "standard",
        "standing",
        "stands",
        "stark",
        "start",
        "started",
        "starting",
        "starts",
        "state",
        "statement",
        "static",
        "station",
        "status",
        "stay",
        "stayed",
        "staying",
        "stays",
        "steady",
        "steep",
        "step",
        "stern",
        "sticky",
        "stiff",
        "still",
        "stirring",
        "stock",
        "stolen",
        "stop",
        "stopped",
        "stopping",
        "stops",
        "storage",
        "story",
        "straight",
        "strange",
        "strangely",
        "strategic",
        "strategy",
        "strength",
        "strict",
        "strictly",
        "striking",
        "strong",
        "strongly",
        "structural",
        "structure",
        "struggle",
        "student",
        "stunning",
        "stupid",
        "sturdy",
        "style",
        "stylish",
        "subject",
        "substance",
        "substitute",
        "subtle",
        "success",
        "successful",
        "such",
        "sudden",
        "suddenly",
        "sufficient",
        "sufficiently",
        "suggest",
        "suggested",
        "suggesting",
        "suggests",
        "suitable",
        "suitably",
        "summer",
        "sun",
        "sunny",
        "super",
        "superb",
        "superior",
        "supply",
        "support",
        "supported",
        "supporting",
        "supports",
        "suppose",
        "supposed",
        "supposes",
        "supposing",
        "sure",
        "surely",
        "surface",
        "surplus",
        "surprise",
        "surprised",
        "surprising",
        "surprisingly",
        "surroundings",
        "survey",
        "suspicious",
        "suspiciously",
        "sustained",
        "sweet",
        "swift",
        "symbolic",
        "sympathetic",
        "symptomatic",
        "system",
        "tactical",
        "take",
        "taken",
        "takes",
        "taking",
        "talk",
        "talked",
        "talking",
        "talks",
        "tall",
        "tame",
        "tangible",
        "target",
        "targeted",
        "task",
        "taste",
        "tasty",
        "teach",
        "teaching",
        "team",
        "technical",
        "technique",
        "technology",
        "tell",
        "telling",
        "tells",
        "ten",
        "tend",
        "tended",
        "tender",
        "tending",
        "tends",
        "tense",
        "tenth",
        "term",
        "terminal",
        "terrible",
        "terribly",
        "terrific",
        "test",
        "tested",
        "testing",
        "tests",
        "testy",
        "text",
        "than",
        "thank",
        "thanks",
        "that",
        "that's",
        "the",
        "their",
        "theirs",
        "them",
        "theme",
        "themselves",
        "then",
        "theory",
        "there",
        "there's",
        "thereafter",
        "thereby",
        "therefore",
        "these",
        "they",
        "they'll",
        "they're",
        "they've",
        "thick",
        "thin",
        "thing",
        "things",
        "think",
        "thinking",
        "thinks",
        "third",
        "thirteen",
        "thirty",
        "this",
        "thorough",
        "thoroughly",
        "those",
        "though",
        "thought",
        "thoughtful",
        "thousand",
        "three",
        "threshold",
        "threw",
        "thrilling",
        "thriving",
        "through",
        "throughout",
        "throw",
        "throwing",
        "thrown",
        "throws",
        "thus",
        "tidy",
        "tie",
        "tight",
        "tightly",
        "till",
        "time",
        "times",
        "tiny",
        "tip",
        "tired",
        "tiresome",
        "title",
        "to",
        "together",
        "token",
        "told",
        "tolerant",
        "tone",
        "too",
        "took",
        "top",
        "topic",
        "topical",
        "total",
        "totally",
        "touch",
        "tough",
        "toward",
        "towards",
        "track",
        "tradition",
        "traditional",
        "traffic",
        "tragic",
        "training",
        "tranquil",
        "transfer",
        "transformation",
        "transition",
        "transparent",
        "traumatic",
        "treatment",
        "tremendous",
        "trend",
        "trial",
        "trick",
        "trip",
        "triple",
        "trivial",
        "tropical",
        "trouble",
        "troubled",
        "true",
        "truly",
        "trust",
        "trusted",
        "trustworthy",
        "truth",
        "truthful",
        "try",
        "trying",
        "tue",
        "tuesday",
        "turn",
        "turned",
        "turning",
        "turns",
        "twelfth",
        "twelve",
        "twentieth",
        "twenty",
        "twice",
        "two",
        "type",
        "typical",
        "typically",
        "ugly",
        "uh",
        "uhh",
        "uhuh",
        "ultimate",
        "ultimately",
        "um",
        "unable",
        "unanimous",
        "unaware",
        "uncomfortable",
        "uncommon",
        "unconscious",
        "under",
        "underlying",
        "underneath",
        "understand",
        "understanding",
        "understands",
        "understood",
        "undoubtedly",
        "uneasy",
        "unemployed",
        "unexpected",
        "unexpectedly",
        "unfair",
        "unfit",
        "unfortunate",
        "unfortunately",
        "unhappy",
        "uniform",
        "unique",
        "unit",
        "united",
        "unity",
        "universal",
        "universally",
        "unknown",
        "unless",
        "unlike",
        "unlikely",
        "unnecessary",
        "unpleasant",
        "unpredictable",
        "unsure",
        "until",
        "unusual",
        "unusually",
        "up",
        "upcoming",
        "upon",
        "upper",
        "upright",
        "upset",
        "urban",
        "urgent",
        "urgently",
        "us",
        "use",
        "used",
        "useful",
        "useless",
        "user",
        "uses",
        "using",
        "usual",
        "usually",
        "utterly",
        "vacant",
        "vague",
        "vaguely",
        "valid",
        "validity",
        "valuable",
        "value",
        "variable",
        "variation",
        "variety",
        "vast",
        "vastly",
        "verbal",
        "verbally",
        "version",
        "vertical",
        "vertically",
        "very",
        "viable",
        "vibrant",
        "vicious",
        "victim",
        "victorious",
        "view",
        "vigorous",
        "vigorously",
        "virtual",
        "virtually",
        "visible",
        "visibly",
        "vision",
        "visit",
        "visual",
        "vital",
        "vivid",
        "vocal",
        "voice",
        "volatile",
        "volume",
        "voluntary",
        "vulnerable",
        "wait",
        "waited",
        "waiting",
        "waits",
        "walk",
        "walked",
        "walking",
        "walks",
        "want",
        "wanted",
        "wanting",
        "wants",
        "warm",
        "warmly",
        "wary",
        "was",
        "wasn't",
        "wasteful",
        "watch",
        "watches",
        "watching",
        "water",
        "way",
        "ways",
        "we",
        "we'll",
        "we're",
        "we've",
        "weak",
        "weakly",
        "wealth",
        "wealthy",
        "wed",
        "wednesday",
        "week",
        "weekday",
        "weekend",
        "weekly",
        "weight",
        "weird",
        "welcome",
        "welfare",
        "well",
        "went",
        "were",
        "weren't",
        "western",
        "wet",
        "what",
        "what's",
        "whatever",
        "when",
        "whenever",
        "where",
        "where's",
        "whereas",
        "wherever",
        "whether",
        "which",
        "while",
        "who",
        "who's",
        "whoa",
        "whoever",
        "whole",
        "wholly",
        "whom",
        "whose",
        "why",
        "why's",
        "wide",
        "widely",
        "widespread",
        "width",
        "wild",
        "will",
        "willing",
        "willingly",
        "win",
        "winning",
        "wins",
        "winter",
        "wisdom",
        "wise",
        "wisely",
        "wish",
        "wished",
        "wishes",
        "wishing",
        "with",
        "within",
        "without",
        "witness",
        "won",
        "won't",
        "wonder",
        "wondered",
        "wonderful",
        "wonderfully",
        "wondering",
        "wonders",
        "word",
        "work",
        "worked",
        "working",
        "works",
        "world",
        "worldwide",
        "worried",
        "worry",
        "worrying",
        "worth",
        "worthwhile",
        "worthy",
        "would",
        "would've",
        "wouldn't",
        "wound",
        "wounded",
        "wow",
        "write",
        "writes",
        "writing",
        "written",
        "wrong",
        "wrongly",
        "wrote",
        "year",
        "yearly",
        "yellow",
        "yes",
        "yesterday",
        "yet",
        "you",
        "you'll",
        "you're",
        "you've",
        "young",
        "your",
        "yours",
        "yourself",
        "yourselves",
        "youthful",
        "yup",
        "zealous",
        "zero",
    })

    @staticmethod
    def _extract_candidates(text: str) -> list[str]:
        """Extract potential entity names using a mask-based approach.

        Assumes ALL words are potential entities, then strips out words
        that are provably NOT entities (articles, pronouns, prepositions,
        conjunctions, verbs, adjectives, adverbs, discourse markers, etc.)
        using a comprehensive mask of 2,226 English words.

        Consecutive non-masked words are grouped into multi-word phrases.
        Returns at most 10 candidates, deduplicated.
        """
        if not text:
            return []

        seen: set[str] = set()
        candidates: list[str] = []
        current_phrase: list[str] = []
        stop = GBrainMemoryProvider._STOP_WORDS

        for token in text.split():
            # Strip leading/trailing punctuation — keep internal hyphens/apostrophes
            clean = token.strip(".,!?;:()[]{}«»""`´~@#$%^&*=+<>/\\|¬·–—")
            if not clean:
                continue

            if clean.lower() in stop:
                # Flush accumulated phrase
                if current_phrase:
                    phrase = " ".join(current_phrase)
                    if phrase.lower() not in seen:
                        seen.add(phrase.lower())
                        candidates.append(phrase)
                    current_phrase = []
            else:
                current_phrase.append(clean)

        # Flush final phrase
        if current_phrase:
            phrase = " ".join(current_phrase)
            if phrase.lower() not in seen:
                candidates.append(phrase)

        return candidates[:10]

    def _search_entity(self, name: str) -> str:
        """Search GBrain for an entity name. Return formatted context or ''."""
        if not self._mcp:
            return ""
        try:
            result = self._mcp.call("search", {"query": name, "limit": 3})
            content_list = result.get("content", [])
            for c in content_list:
                text = c.get("text", "")
                if not text:
                    continue
                # Try to parse as structured JSON
                try:
                    data = json.loads(text)
                    if isinstance(data, list) and data:
                        # Return compiled_truth from top 2 matches
                        lines = [f"## Brain context for \"{name}\"", ""]
                        for item in data[:2]:
                            slug = item.get("slug", "")
                            title = item.get("title", slug)
                            chunk = item.get("chunk_text", "")
                            page_type = item.get("type", "")
                            # Truncate long chunks
                            if len(chunk) > 600:
                                chunk = chunk[:600] + "..."
                            lines.append(
                                f"**{title}** (/{slug}, {page_type})"
                            )
                            lines.append(chunk)
                            lines.append("")
                        return "\n".join(lines)
                except (json.JSONDecodeError, TypeError):
                    pass
                # Fallback: return raw text (capped)
                if len(text) > 1200:
                    text = text[:1200] + "..."
                return f"## Brain context for \"{name}\"\n\n{text}"
        except Exception as e:
            logger.debug("_search_entity failed for %r: %s", name, e)
        return ""

    def _resolve_entities(self, text: str) -> list[dict]:
        """Extract entity names and resolve to brain slugs + types.

        Returns list of {name, slug, type} dicts.
        """
        candidates = self._extract_candidates(text)
        if not candidates:
            return []

        resolved: list[dict] = []
        seen_slugs: set[str] = set()

        for name in candidates[:5]:
            try:
                result = self._mcp.call("search", {"query": name, "limit": 3})
                content_texts = [
                    c.get("text", "")
                    for c in result.get("content", [])
                    if c.get("text")
                ]
                for raw in content_texts:
                    try:
                        data = json.loads(raw)
                        if isinstance(data, list):
                            for item in data:
                                page_type = item.get("type", "")
                                if page_type not in ("person", "company"):
                                    continue
                                slug = item.get("slug", "")
                                title = item.get("title", "")
                                if not slug or slug in seen_slugs:
                                    continue
                                # Verify the candidate name matches the page title
                                name_lower = name.lower()
                                title_lower = title.lower()
                                if not (name_lower in title_lower
                                        or title_lower.startswith(name_lower)
                                        or name_lower.replace(" ", "-") in slug.lower()):
                                    continue
                                resolved.append({
                                    "name": name,
                                    "slug": slug,
                                    "type": page_type,
                                })
                                seen_slugs.add(slug)
                    except (json.JSONDecodeError, TypeError):
                        # Fallback: extract slugs from wiki-link markdown
                        for match in re.finditer(
                            r'\[([^\]]+)\]\(/([^)]+)\)', raw
                        ):
                            slug = match.group(2)
                            if slug not in seen_slugs:
                                resolved.append({
                                    "name": name,
                                    "slug": slug,
                                    "type": "unknown",
                                })
                                seen_slugs.add(slug)
            except Exception as e:
                logger.debug("_resolve_entities search failed for %r: %s", name, e)

        return resolved[:5]

    @property
    def name(self) -> str:
        return "gbrain"

    def get_config_schema(self) -> list[dict[str, Any]]:
        return [
            {
                "key": "url",
                "description": "GBrain MCP endpoint URL",
                "default": _DEFAULT_URL,
            },
            {
                "key": "api_token",
                "description": "GBrain MCP API bearer token",
                "secret": True,
                "env_var": "MCP_GBRAIN_API_KEY",
                "required": True,
            },
            {
                "key": "timeout",
                "description": "Request timeout in seconds",
                "default": _DEFAULT_TIMEOUT,
            },
        ]

    def save_config(self, values: dict[str, Any], hermes_home: str) -> None:
        path = Path(hermes_home) / "gbrain_memory.json"
        existing = {}
        if path.exists():
            try:
                existing = json.loads(path.read_text())
            except (json.JSONDecodeError, OSError):
                pass
        existing["url"] = values.get("url", existing.get("url", _DEFAULT_URL))
        existing["timeout"] = int(values.get("timeout", existing.get("timeout", _DEFAULT_TIMEOUT)))
        path.write_text(json.dumps(existing, indent=2) + "\n")

    def is_available(self) -> bool:
        """Check config only — NO network calls (per MemoryProvider contract)."""
        cfg = _load_config()
        return bool(cfg.get("api_token"))

    def initialize(self, session_id: str, **kwargs) -> None:
        self._config = _load_config()
        url = self._config["url"]
        token = self._config["api_token"]
        timeout = self._config["timeout"]
        if not token:
            logger.warning("GBrain not configured: missing api_token")
            return
        self._mcp = _McpClient(url, token, timeout)
        logger.info("GBrain initialized — %d hardcoded tool schemas", len(HARDCODED_SCHEMA_DICTS))

    def shutdown(self) -> None:
        if self._mcp:
            self._mcp.close()
            self._mcp = None

    def get_tool_schemas(self) -> list[dict[str, Any]]:
        """Return hardcoded tool schemas — no dynamic discovery needed."""
        return list(HARDCODED_SCHEMA_DICTS)

    def handle_tool_call(self, tool_name: str, args: dict[str, Any], **kwargs) -> str:
        if not self._mcp:
            return json.dumps({"error": "GBrain not initialized"})
        try:
            schema = HARDCODED_SCHEMAS.get(tool_name)
            if not schema:
                return json.dumps({"error": f"Unknown gbrain tool: {tool_name}"})
            mcp_name = schema["mcp_name"]
            result = self._mcp.call(mcp_name, args)
            content_list = result.get("content", [])
            texts = [c["text"] for c in content_list if c.get("type") == "text"]
            return "\n".join(texts) if texts else json.dumps(result)
        except _McpError as e:
            return json.dumps({"error": str(e)})
        except Exception as e:
            logger.exception("GBrain tool call failed: %s", tool_name)
            return json.dumps({"error": f"{type(e).__name__}: {e}"})

    def system_prompt_block(self) -> str:
        names = [s["name"] for s in HARDCODED_SCHEMA_DICTS[:8]]
        return (
            "## GBrain Persistent Memory\n"
            "You have persistent memory via GBrain. The gbrain_* tools let you "
            "search, save, and reason across your knowledge base. Available tools: "
            f"{', '.join(names)}, and more."
        )

    # ── brain-agent-loop: READ step (per guide — read brain BEFORE responding) ──

    def prefetch(self, query: str, *, session_id: str = "") -> str:
        """Search GBrain for entities in the current message SYNCHRONOUSLY.

        Per the brain-agent-loop guide: "Read BEFORE responding, not after."
        Extracts entity names from the current message, searches GBrain for
        each, and returns formatted context for injection into the model's
        system prompt — all within the same turn.

        The search is capped at ~1s total (up to 3 entity lookups) so the
        latency hit is minimal. Providers with no entities to look up return
        immediately.
        """
        if not self._mcp or not query:
            return ""
        candidates = self._extract_candidates(query)
        if not candidates:
            return ""

        context_parts = []
        for name in candidates[:3]:  # cap at 3 to keep latency low
            ctx = self._search_entity(name)
            if ctx:
                context_parts.append(ctx)

        if not context_parts:
            return ""

        logger.info(
            "brain-loop prefetch: %d entities detected, %d context blocks returned "
            "(candidates=%r)", len(candidates), len(context_parts), candidates[:5]
        )

        return (
            "## GBrain — automatically detected context\n\n"
            + "\n---\n\n".join(context_parts)
        )

    def queue_prefetch(self, query: str, *, session_id: str = "") -> None:
        """Warm the brain cache for the NEXT turn (optional — runs in background).

        Called after each turn completes. Searches the current message's
        entities so the next turn's prefetch() may benefit from cached
        results, but the primary read path is prefetch() which runs
        synchronously on the current turn.
        """
        # No-op: the primary read happens synchronously in prefetch().
        # This hook is left available for future cache-warming use.
        pass

    def _write_timeline(self, slug: str, today_str: str) -> None:
        """Add a timeline entry for a resolved entity slug."""
        if not self._mcp:
            return
        try:
            self._mcp.call("add_timeline_entry", {
                "slug": slug,
                "date": today_str,
                "summary": f"Mentioned in conversation on {today_str}",
                "source": "hermes-brain-loop",
            })
            logger.info("brain-loop: added timeline to /%s", slug)
        except Exception as e:
            logger.debug("brain-loop: timeline write failed for /%s: %s", slug, e)

    # ── brain-agent-loop: WRITE step ──────────────────────────────────

    def sync_turn(
        self,
        user_content: str,
        assistant_content: str,
        *,
        session_id: str = "",
        messages=None,
    ) -> None:
        """Write timeline entries for entities mentioned in the conversation.

        Called after each turn completes. Already runs on a background
        worker thread via memory_manager's ThreadPoolExecutor — no
        additional daemon thread needed.
        """
        if not self._mcp or not user_content:
            return

        today_str = date.today().isoformat()
        try:
            entities = self._resolve_entities(user_content)
            for e in entities:
                self._write_timeline(e["slug"], today_str)
        except Exception as e:
            logger.debug("brain-loop sync_turn background failed: %s", e)


def register(ctx) -> None:
    ctx.register_memory_provider(GBrainMemoryProvider())
