"""Hardcoded GBrain MCP tool schemas.

Generated from live server at gbrain.plainrandom.com on 2026-06-16.
Server version: 0.42.44.0
Total tools: 83
"""

HARDCODED_SCHEMAS = {
    "gbrain_get_page": {
        "name": "gbrain_get_page",
        "mcp_name": "get_page",
        "description": "Read a page by slug (supports optional fuzzy matching). Soft-deleted pages are hidden by default; pass include_deleted: true to surface them with deleted_at populated (see v0.26.5 recovery window).",
        "parameters": {"type": "object", "properties": {"slug": {"type": "string", "description": "Page slug"}, "fuzzy": {"type": "boolean", "description": "Enable fuzzy slug resolution (default: false)"}, "include_deleted": {"type": "boolean", "description": "v0.26.5: surface soft-deleted pages with deleted_at populated (default: false). Used by restore workflows."}}, "required": ["slug"]},
    },
    "gbrain_put_page": {
        "name": "gbrain_put_page",
        "mcp_name": "put_page",
        "description": "Write/update a page (markdown with frontmatter). Chunks, embeds, reconciles tags, and (when auto_link/auto_timeline are enabled) extracts + reconciles graph links and timeline entries. For large content on Windows (pipe-buffer limit ~45KB) or any file-as-input workflow, use `gbrain capture --file PATH --slug SLUG` — capture reads the file as a Buffer with a binary-NUL guard and adds provenance write-through (v0.39.3.0).",
        "parameters": {"type": "object", "properties": {"slug": {"type": "string", "description": "Page slug"}, "content": {"type": "string", "description": "Full markdown content with YAML frontmatter"}, "source_kind": {"type": "string", "description": "Ingestion channel taxonomy (capture-cli | put_page | webhook | \u2026). Remote callers: SERVER-STAMPED, client value ignored."}, "source_uri": {"type": "string", "description": "Original URI/path/message-id the event carried. Remote callers: SERVER-STAMPED null."}, "ingested_via": {"type": "string", "description": "Richer label paired with source_kind. Remote callers: SERVER-STAMPED."}}, "required": ["slug", "content"]},
    },
    "gbrain_delete_page": {
        "name": "gbrain_delete_page",
        "mcp_name": "delete_page",
        "description": "Soft-delete a page. The row is hidden from search and from get_page/list_pages, but is recoverable via restore_page within 72h. The autopilot purge phase hard-deletes after the recovery window. Pass include_deleted: true to get_page to verify the soft-delete landed.",
        "parameters": {"type": "object", "properties": {"slug": {"type": "string"}}, "required": ["slug"]},
    },
    "gbrain_list_pages": {
        "name": "gbrain_list_pages",
        "mcp_name": "list_pages",
        "description": "List pages with optional filters. For 'what's recent / what did I touch this week' questions, use list_pages with sort=updated_desc instead of semantic search.",
        "parameters": {"type": "object", "properties": {"type": {"type": "string", "description": "Filter by page type"}, "tag": {"type": "string", "description": "Filter by tag"}, "limit": {"type": "number", "description": "Max results (default 50)"}, "updated_after": {"type": "string", "description": "ISO date (YYYY-MM-DD) or full timestamp. Returns pages with updated_at > value."}, "sort": {"type": "string", "description": "Sort order. Default updated_desc (matches pre-v0.29). Options: updated_desc, updated_asc, created_desc, slug.", "enum": ["updated_desc", "updated_asc", "created_desc", "slug"]}, "include_deleted": {"type": "boolean", "description": "v0.26.5: include soft-deleted pages (default: false). Used by restore workflows and operator diagnostics."}}, "required": []},
    },
    "gbrain_restore_page": {
        "name": "gbrain_restore_page",
        "mcp_name": "restore_page",
        "description": "v0.26.5 — restore a soft-deleted page (clear deleted_at). Returns success only if the page was actually soft-deleted. After this op, the page reappears in search and in get_page/list_pages without the include_deleted flag.",
        "parameters": {"type": "object", "properties": {"slug": {"type": "string"}}, "required": ["slug"]},
    },
    "gbrain_search": {
        "name": "gbrain_search",
        "mcp_name": "search",
        "description": "Keyword search using full-text search. For personal/emotional questions, prefer get_recent_salience or find_anomalies — they surface activity bursts without needing a search term. For code-symbol questions (callers, callees, definitions, blast radius), use code_callers / code_callees / code_def / code_refs instead — those return structural graph data, not text chunks.",
        "parameters": {"type": "object", "properties": {"query": {"type": "string"}, "limit": {"type": "number", "description": "Max results (default 20)"}, "offset": {"type": "number", "description": "Skip first N results (for pagination)"}, "mode": {"type": "string", "description": "Search mode (conservative|balanced|tokenmax). Local callers only."}}, "required": ["query"]},
    },
    "gbrain_query": {
        "name": "gbrain_query",
        "mcp_name": "query",
        "description": "Hybrid search with vector + keyword + multi-query expansion. For personal/emotional questions ('what's going on with me', 'anything notable', 'how am I feeling'), prefer get_recent_salience, find_anomalies, or get_recent_transcripts. Semantic search returns polished pages and misses recent activity bursts. Do NOT assume words like 'crazy', 'notable', or 'big' mean impressive — they often mean difficult or emotionally charged.",
        "parameters": {"type": "object", "properties": {"query": {"type": "string"}, "image": {"type": "string", "description": "Base64-encoded image bytes for image-similarity search (CLI: --image <path>)."}, "image_mime": {"type": "string", "description": "MIME type for the image bytes (auto-derived from path on CLI; required when calling op directly)."}, "limit": {"type": "number", "description": "Max results (default 20)"}, "offset": {"type": "number", "description": "Skip first N results (for pagination)"}, "expand": {"type": "boolean", "description": "Enable multi-query expansion (default: true)"}, "detail": {"type": "string", "description": "Result detail level: low (compiled truth only), medium (default, all with dedup), high (all chunks)"}, "mode": {"type": "string", "description": "Search mode (conservative|balanced|tokenmax). Local callers only; remote uses configured mode."}, "lang": {"type": "string", "description": "Filter to chunks where content_chunks.language matches (e.g., typescript, python, ruby)"}, "symbol_kind": {"type": "string", "description": "Filter to chunks where content_chunks.symbol_type matches (e.g., function, class, method, type, interface)"}, "near_symbol": {"type": "string", "description": "Anchor retrieval at this qualified symbol name (e.g., BrainEngine.searchKeyword). Enables A2 two-pass."}, "walk_depth": {"type": "number", "description": "Structural walk depth 1-2. Default 0 (off). Expands anchors through code_edges with 1/(1+hop) decay."}, "salience": {"type": "string", "description": "v0.29.1 salience boost \u2014 emotional_weight + take_count, NO time component.\n  'off' \u2014 default for entity / canonical / definitional queries\n  'on'  \u2014 surface emotionally-weighted + take-rich pages\n  'strong' \u2014 aggressive mattering tilt\nOmit and gbrain auto-detects from query text. Independent of `recency`.", "enum": ["off", "on", "strong"]}, "recency": {"type": "string", "description": "v0.29.1 recency boost \u2014 per-prefix age decay, NO mattering signal.\n  'off' \u2014 default for canonical truth\n  'on'  \u2014 daily/, media/x/, chat/ decay aggressively; concepts/, originals/, writing/ stay evergreen\n  'strong' \u2014 multiplies the recency factor by 1.5 (use for 'today' / 'right now')\nOmit and gbrain auto-detects. Independent of `salience` (orthogonal axes).", "enum": ["off", "on", "strong"]}, "since": {"type": "string", "description": "v0.29.1 \u2014 filter to pages whose effective_date is >= this. ISO-8601 (YYYY-MM-DD or full timestamp) OR relative ('7d', '2w', '1y'). Replaces deprecated `afterDate`."}, "until": {"type": "string", "description": "v0.29.1 \u2014 filter to effective_date <= this. Same format as `since`. Replaces deprecated `beforeDate`. YYYY-MM-DD lands at end-of-day."}, "source_id": {"type": "string", "description": "v0.34: scope search to a single source. Defaults to OperationContext.sourceId (set from CLI --source / GBRAIN_SOURCE / .gbrain-source dotfile). Pass '__all__' to span every source for trusted local callers; for remote callers '__all__' spans only your granted sources."}, "cross_modal": {"type": "string", "description": "v0.36 cross-modal search routing.\n  'text' (default for non-image-intent queries) \u2014 text-only path, no behavior change vs v0.35.\n  'image' \u2014 route the query through Voyage multimodal-3 + the embedding_image column. Best for 'show me photos of...' phrasings.\n  'both' \u2014 run text AND image searches in parallel; merge via weighted RRF.\n  'auto' \u2014 same effect as omitting the field; intent classifier decides based on query phrasing.", "enum": ["text", "image", "both", "auto"]}, "embedding_column": {"type": "string", "description": "v0.36: route vector search through a non-default embedding column. Defaults to 'embedding' (OpenAI 1536d) unless `search_embedding_column` config sets a different default. Per-call override for A/B benchmarking across providers (e.g. 'embedding_voyage', 'embedding_zeroentropy'). Column MUST be declared in the `embedding_columns` config registry \u2014 unknown names throw with a paste-ready hint listing valid columns."}, "adaptive_return": {"type": "boolean", "description": "v0.41.33 \u2014 return a TIGHT, intent-sized result set instead of the full top-K. YOU (the agent) set this per query to serve the user well:\n  TRUE when the user's question has a small, specific answer \u2014 a lookup ('what is X', 'who is Y', 'what's my <thing>', 'what did Z decide'), a single-fact recall, or when you'll route the result into a precise downstream step (a classifier, a decision, an exact citation). The user gets the answer, not a wall of loosely-related pages, and you spend fewer tokens reading noise.\n  Omit / FALSE for breadth \u2014 'everything about X', 'list all', 'what do I know about Y', exploration, brainstorming, or any time you'd rather see more candidates and judge for yourself. Recall matters more there, so take the full top-K.\nSafe by construction: it NEVER returns empty when there are matches (you always get at least the top hit), and it only applies to the first page (omit when paginating). Caps come from config (search.adaptive_return_entity_max / _other_max; default 2 / 6) \u2014 pass `limit` 1 alongside this for a hard single-answer cap."}, "autocut": {"type": "boolean", "description": "v0.42.3.0 \u2014 autocut is the SMART DEFAULT (already ON when the reranker runs, which it does in the default search mode). It returns only the confident cluster by cutting where the relevance score drops off a cliff, so an obvious single answer comes back as 1 result and a genuine handful comes back as that handful \u2014 not a fixed wall of 20+.\n  You almost never set this. Pass FALSE only to FORCE the full top-K when you deliberately want breadth \u2014 broad exploration, 'show me everything about X', enumeration where you'd rather over-collect and judge for yourself, or when you suspect the top hit is wrong and want to see the alternatives.\n  TRUE is redundant in default mode (it's already on); it only matters to override a brain whose config turned autocut off.\nSafe by construction: never returns empty when there are matches, only applies to the first page (omit when paginating), and is a no-op when no reranker scored the results (so it can't cut on an untrustworthy signal). Distinct from `adaptive_return`: autocut cuts on the score cliff; adaptive_return caps by question intent. Leave both unset for the smart default."}, "relational": {"type": "boolean", "description": "v0.43 \u2014 relational recall arm. SMART DEFAULT (on in balanced/tokenmax). When the question is about a RELATIONSHIP ('who invested in widget-co', 'who introduced me to alice', 'what connects fund-a and fund-b'), the brain resolves the named entity and walks its typed-edge graph (invested_in, works_at, founded, \u2026), surfacing the answer even when no passage mentions both sides. Pure no-op for non-relational questions. Pass FALSE to force lexical/vector-only retrieval (e.g. debugging why a graph answer appeared). You almost never set this."}}, "required": []},
    },
    "gbrain_search_by_image": {
        "name": "gbrain_search_by_image",
        "mcp_name": "search_by_image",
        "description": "v0.36 cross-modal Phase 2: image-as-query retrieval. Accepts a local path (CLI), data: URI, or http(s):// URL (SSRF-defended). Returns visually-similar image chunks plus any OCR text they carry. Optional `query` text refinement merges via weighted RRF (D13 hybrid intersect). True image→full-text-knowledge requires Phase 3 (`gbrain reindex --multimodal` + `search.unified_multimodal: true`).",
        "parameters": {"type": "object", "properties": {"image_path": {"type": "string", "description": "Absolute path to image (local CLI callers only \u2014 rejected for remote MCP per D18)."}, "image_url": {"type": "string", "description": "http(s):// URL to image. SSRF-defended; max 3 redirect hops; 10MB cap."}, "image_data": {"type": "string", "description": "Base64-encoded image bytes (preferred for remote MCP callers). PNG/JPEG/WebP only."}, "image_mime": {"type": "string", "description": "Optional MIME hint when ambiguous. Magic-byte sniff is authoritative."}, "query": {"type": "string", "description": "Optional text refinement; runs hybrid intersect via D13 weighted RRF."}, "limit": {"type": "number", "description": "Max results (default 20)"}, "offset": {"type": "number", "description": "Skip first N results (for pagination)"}, "source_id": {"type": "string", "description": "Scope to a single source. Defaults to ctx.sourceId. '__all__' spans every source for trusted local callers, your granted sources for remote callers."}}, "required": []},
    },
    "gbrain_add_tag": {
        "name": "gbrain_add_tag",
        "mcp_name": "add_tag",
        "description": "Add tag to page",
        "parameters": {"type": "object", "properties": {"slug": {"type": "string"}, "tag": {"type": "string"}}, "required": ["slug", "tag"]},
    },
    "gbrain_remove_tag": {
        "name": "gbrain_remove_tag",
        "mcp_name": "remove_tag",
        "description": "Remove tag from page",
        "parameters": {"type": "object", "properties": {"slug": {"type": "string"}, "tag": {"type": "string"}}, "required": ["slug", "tag"]},
    },
    "gbrain_get_tags": {
        "name": "gbrain_get_tags",
        "mcp_name": "get_tags",
        "description": "List tags for a page",
        "parameters": {"type": "object", "properties": {"slug": {"type": "string"}}, "required": ["slug"]},
    },
    "gbrain_add_link": {
        "name": "gbrain_add_link",
        "mcp_name": "add_link",
        "description": "Create link between pages",
        "parameters": {"type": "object", "properties": {"from": {"type": "string"}, "to": {"type": "string"}, "link_type": {"type": "string", "description": "Link type (e.g., invested_in, works_at)"}, "context": {"type": "string", "description": "Context for the link"}, "link_source": {"type": "string", "description": "Provenance tag (kebab-case, e.g. 'citation-graph'). Defaults to 'manual'. Reconciliation-managed built-ins (markdown/frontmatter/mentions/wikilink-resolved) are rejected."}}, "required": ["from", "to"]},
    },
    "gbrain_remove_link": {
        "name": "gbrain_remove_link",
        "mcp_name": "remove_link",
        "description": "Remove link between pages",
        "parameters": {"type": "object", "properties": {"from": {"type": "string"}, "to": {"type": "string"}, "link_type": {"type": "string", "description": "Only remove edges of this link type (omit = all types)"}, "link_source": {"type": "string", "description": "Only remove edges of this provenance (e.g. citation-graph); omit = any provenance"}}, "required": ["from", "to"]},
    },
    "gbrain_get_links": {
        "name": "gbrain_get_links",
        "mcp_name": "get_links",
        "description": "List outgoing links from a page",
        "parameters": {"type": "object", "properties": {"slug": {"type": "string"}}, "required": ["slug"]},
    },
    "gbrain_get_backlinks": {
        "name": "gbrain_get_backlinks",
        "mcp_name": "get_backlinks",
        "description": "List incoming links to a page",
        "parameters": {"type": "object", "properties": {"slug": {"type": "string"}}, "required": ["slug"]},
    },
    "gbrain_list_link_sources": {
        "name": "gbrain_list_link_sources",
        "mcp_name": "list_link_sources",
        "description": "List distinct link_source provenances in the brain with edge counts (e.g. citation-graph, manual, markdown)",
        "parameters": {"type": "object", "properties": {}, "required": []},
    },
    "gbrain_traverse_graph": {
        "name": "gbrain_traverse_graph",
        "mcp_name": "traverse_graph",
        "description": "Traverse link graph from a page. With link_type/direction, returns edges (GraphPath[]) instead of nodes.",
        "parameters": {"type": "object", "properties": {"slug": {"type": "string"}, "depth": {"type": "number", "description": "Max traversal depth (default 5, capped at 10)"}, "link_type": {"type": "string", "description": "Filter to one link type (per-edge filter, traversal only follows matching edges)"}, "direction": {"type": "string", "description": "Traversal direction (default out)", "enum": ["in", "out", "both"]}}, "required": ["slug"]},
    },
    "gbrain_add_timeline_entry": {
        "name": "gbrain_add_timeline_entry",
        "mcp_name": "add_timeline_entry",
        "description": "Add timeline entry to a page",
        "parameters": {"type": "object", "properties": {"slug": {"type": "string"}, "date": {"type": "string"}, "summary": {"type": "string"}, "detail": {"type": "string"}, "source": {"type": "string"}}, "required": ["slug", "date", "summary"]},
    },
    "gbrain_get_timeline": {
        "name": "gbrain_get_timeline",
        "mcp_name": "get_timeline",
        "description": "Get timeline entries for a page",
        "parameters": {"type": "object", "properties": {"slug": {"type": "string"}}, "required": ["slug"]},
    },
    "gbrain_get_stats": {
        "name": "gbrain_get_stats",
        "mcp_name": "get_stats",
        "description": "Brain statistics (page count, chunk count, etc.)",
        "parameters": {"type": "object", "properties": {}, "required": []},
    },
    "gbrain_get_health": {
        "name": "gbrain_get_health",
        "mcp_name": "get_health",
        "description": "Brain health dashboard (embed coverage, stale pages, orphans)",
        "parameters": {"type": "object", "properties": {}, "required": []},
    },
    "gbrain_run_doctor": {
        "name": "gbrain_run_doctor",
        "mcp_name": "run_doctor",
        "description": "Run brain health checks and return a structured DoctorReport (thin-client doctor surface).",
        "parameters": {"type": "object", "properties": {}, "required": []},
    },
    "gbrain_get_versions": {
        "name": "gbrain_get_versions",
        "mcp_name": "get_versions",
        "description": "Page version history",
        "parameters": {"type": "object", "properties": {"slug": {"type": "string"}}, "required": ["slug"]},
    },
    "gbrain_revert_version": {
        "name": "gbrain_revert_version",
        "mcp_name": "revert_version",
        "description": "Revert page to a previous version",
        "parameters": {"type": "object", "properties": {"slug": {"type": "string"}, "version_id": {"type": "number"}}, "required": ["slug", "version_id"]},
    },
    "gbrain_get_brain_identity": {
        "name": "gbrain_get_brain_identity",
        "mcp_name": "get_brain_identity",
        "description": "Brain identity + counters for thin-client banner. Returns version, engine kind, and page/chunk counts. Read-scope.",
        "parameters": {"type": "object", "properties": {}, "required": []},
    },
    "gbrain_list_skills": {
        "name": "gbrain_list_skills",
        "mcp_name": "list_skills",
        "description": "List the skills this agent's brain publishes. A skill is a named prose instruction set (NOT executable code) that teaches you how to do a task using this server's other tools. Returns a flat catalog — each entry has a name, one-line description, triggers (phrasings that should invoke it), and `usable_tools` / `unavailable_tools` (which tools the skill calls that you CAN vs CANNOT call given this server + your access). To actually use a skill, call get_skill with its name, read the returned prose, and follow it — calling the correspondingly-named tools on THIS server. The response also carries an `instructions` envelope explaining this protocol. Reflects the serving repo's skills even when the call targets a mounted brain. Read-scope; published only when the brain owner enabled mcp.publish_skills.",
        "parameters": {"type": "object", "properties": {"section": {"type": "string", "description": "Optional: only skills whose routing section matches this exactly."}}, "required": []},
    },
    "gbrain_get_skill": {
        "name": "gbrain_get_skill",
        "mcp_name": "get_skill",
        "description": "Fetch one skill's full instructions by name. Returns `{name, frontmatter (sanitized), body, usable_tools, unavailable_tools, client_guidance}`. The `body` is prose — read it as your operating instructions for this task, and when it says to search / store / look something up, call the same-named MCP tool on THIS server. There is nothing to 'execute' — the value is the instructions plus your tool calls back to this server. Tools listed in `unavailable_tools` won't work for you (not exposed here, or beyond your access) — adapt accordingly. Size-capped; read-scope; requires the owner to have enabled mcp.publish_skills.",
        "parameters": {"type": "object", "properties": {"name": {"type": "string", "description": "Skill name exactly as returned by list_skills."}}, "required": ["name"]},
    },
    "gbrain_get_status_snapshot": {
        "name": "gbrain_get_status_snapshot",
        "mcp_name": "get_status_snapshot",
        "description": "Snapshot for `gbrain status` thin-client mode: sync freshness + last cycle. Admin-scope.",
        "parameters": {"type": "object", "properties": {}, "required": []},
    },
    "gbrain_put_raw_data": {
        "name": "gbrain_put_raw_data",
        "mcp_name": "put_raw_data",
        "description": "Store raw API response data for a page",
        "parameters": {"type": "object", "properties": {"slug": {"type": "string"}, "source": {"type": "string", "description": "Data source (e.g., crustdata, happenstance)"}, "data": {"type": "object", "description": "Raw data object"}}, "required": ["slug", "source", "data"]},
    },
    "gbrain_get_raw_data": {
        "name": "gbrain_get_raw_data",
        "mcp_name": "get_raw_data",
        "description": "Retrieve raw data for a page",
        "parameters": {"type": "object", "properties": {"slug": {"type": "string"}, "source": {"type": "string", "description": "Filter by source"}}, "required": ["slug"]},
    },
    "gbrain_resolve_slugs": {
        "name": "gbrain_resolve_slugs",
        "mcp_name": "resolve_slugs",
        "description": "Fuzzy-resolve a partial slug to matching page slugs",
        "parameters": {"type": "object", "properties": {"partial": {"type": "string"}}, "required": ["partial"]},
    },
    "gbrain_get_chunks": {
        "name": "gbrain_get_chunks",
        "mcp_name": "get_chunks",
        "description": "Get content chunks for a page",
        "parameters": {"type": "object", "properties": {"slug": {"type": "string"}}, "required": ["slug"]},
    },
    "gbrain_log_ingest": {
        "name": "gbrain_log_ingest",
        "mcp_name": "log_ingest",
        "description": "Log an ingestion event",
        "parameters": {"type": "object", "properties": {"source_type": {"type": "string"}, "source_ref": {"type": "string"}, "pages_updated": {"type": "array", "items": {"type": "string"}}, "summary": {"type": "string"}}, "required": ["source_type", "source_ref", "pages_updated", "summary"]},
    },
    "gbrain_get_ingest_log": {
        "name": "gbrain_get_ingest_log",
        "mcp_name": "get_ingest_log",
        "description": "Get recent ingestion log entries",
        "parameters": {"type": "object", "properties": {"limit": {"type": "number", "description": "Max entries (default 20)"}}, "required": []},
    },
    "gbrain_submit_job": {
        "name": "gbrain_submit_job",
        "mcp_name": "submit_job",
        "description": "Submit a background job to the Minions queue. Built-in types: sync, embed, lint, import, extract, backlinks, autopilot-cycle. The `shell` type is CLI-only and rejected over MCP.",
        "parameters": {"type": "object", "properties": {"name": {"type": "string", "description": "Job type (sync, embed, lint, import, extract, backlinks, autopilot-cycle; shell is CLI-only)"}, "data": {"type": "object", "description": "Job payload (JSON)"}, "queue": {"type": "string", "description": "Queue name (default: \"default\")"}, "priority": {"type": "number", "description": "Priority (0 = highest, default: 0)"}, "max_attempts": {"type": "number", "description": "Max retry attempts (default: 3)"}, "delay": {"type": "number", "description": "Delay in ms before eligible"}, "timeout_ms": {"type": "number", "description": "Per-job wall-clock timeout in ms; aborted job goes to dead"}}, "required": ["name"]},
    },
    "gbrain_get_job": {
        "name": "gbrain_get_job",
        "mcp_name": "get_job",
        "description": "Get job status and details by ID",
        "parameters": {"type": "object", "properties": {"id": {"type": "number", "description": "Job ID"}}, "required": ["id"]},
    },
    "gbrain_list_jobs": {
        "name": "gbrain_list_jobs",
        "mcp_name": "list_jobs",
        "description": "List jobs with optional filters",
        "parameters": {"type": "object", "properties": {"status": {"type": "string", "description": "Filter by status (waiting, active, completed, failed, delayed, dead, cancelled)"}, "queue": {"type": "string", "description": "Filter by queue name"}, "name": {"type": "string", "description": "Filter by job type"}, "limit": {"type": "number", "description": "Max results (default: 50)"}}, "required": []},
    },
    "gbrain_cancel_job": {
        "name": "gbrain_cancel_job",
        "mcp_name": "cancel_job",
        "description": "Cancel a waiting, active, or delayed job",
        "parameters": {"type": "object", "properties": {"id": {"type": "number", "description": "Job ID"}}, "required": ["id"]},
    },
    "gbrain_retry_job": {
        "name": "gbrain_retry_job",
        "mcp_name": "retry_job",
        "description": "Re-queue a failed or dead job for retry",
        "parameters": {"type": "object", "properties": {"id": {"type": "number", "description": "Job ID"}}, "required": ["id"]},
    },
    "gbrain_get_job_progress": {
        "name": "gbrain_get_job_progress",
        "mcp_name": "get_job_progress",
        "description": "Get structured progress for a running job",
        "parameters": {"type": "object", "properties": {"id": {"type": "number", "description": "Job ID"}}, "required": ["id"]},
    },
    "gbrain_pause_job": {
        "name": "gbrain_pause_job",
        "mcp_name": "pause_job",
        "description": "Pause a waiting, active, or delayed job",
        "parameters": {"type": "object", "properties": {"id": {"type": "number", "description": "Job ID"}}, "required": ["id"]},
    },
    "gbrain_resume_job": {
        "name": "gbrain_resume_job",
        "mcp_name": "resume_job",
        "description": "Resume a paused job back to waiting",
        "parameters": {"type": "object", "properties": {"id": {"type": "number", "description": "Job ID"}}, "required": ["id"]},
    },
    "gbrain_replay_job": {
        "name": "gbrain_replay_job",
        "mcp_name": "replay_job",
        "description": "Replay a completed/failed/dead job, optionally with modified data",
        "parameters": {"type": "object", "properties": {"id": {"type": "number", "description": "Source job ID to replay"}, "data_overrides": {"type": "object", "description": "Data fields to override (merged with original)"}}, "required": ["id"]},
    },
    "gbrain_send_job_message": {
        "name": "gbrain_send_job_message",
        "mcp_name": "send_job_message",
        "description": "Send a sidechannel message to a running job's inbox",
        "parameters": {"type": "object", "properties": {"id": {"type": "number", "description": "Job ID to message"}, "payload": {"type": "object", "description": "Message payload (arbitrary JSON)"}, "sender": {"type": "string", "description": "Sender identity (default: admin)"}}, "required": ["id", "payload"]},
    },
    "gbrain_submit_agent": {
        "name": "gbrain_submit_agent",
        "mcp_name": "submit_agent",
        "description": "Submit an LLM agent job that the worker dispatches via the gateway-native tool loop. Requires the `agent` OAuth scope. Tools, source, slug prefixes, max concurrency, and daily budget are bound at OAuth client registration time.",
        "parameters": {"type": "object", "properties": {"prompt": {"type": "string", "description": "User prompt for the agent"}, "model": {"type": "string", "description": "provider:model string (defaults to models.tier.subagent)"}, "allowed_tools": {"type": "array", "description": "Subset of bound_tools the agent may invoke", "items": {"type": "string"}}, "allowed_slug_prefixes": {"type": "array", "description": "Subset of bound_slug_prefixes for put_page writes", "items": {"type": "string"}}, "max_turns": {"type": "number", "description": "Max LLM turns (default 20, hard cap 100)"}, "queue": {"type": "string", "description": "Queue name (default \"default\")"}}, "required": ["prompt"]},
    },
    "gbrain_find_orphans": {
        "name": "gbrain_find_orphans",
        "mcp_name": "find_orphans",
        "description": "Find pages with no inbound wikilinks. Essential for content enrichment cycles.",
        "parameters": {"type": "object", "properties": {"include_pseudo": {"type": "boolean", "description": "Include auto-generated and pseudo pages (default: false)"}}, "required": []},
    },
    "gbrain_get_calibration_profile": {
        "name": "gbrain_get_calibration_profile",
        "mcp_name": "get_calibration_profile",
        "description": "Read the active calibration profile for a holder. Returns the latest row from calibration_profiles (per-source, per-holder) including Brier score, accuracy, pattern statements, and active bias tags. Source-scoped via sourceScopeOpts — federated_read scopes see the union of allowed sources, scalar source-bound clients see only their source. Returns null when no profile exists yet (cold-brain branch: builds after 5+ resolved takes + a calibration_profile phase run).",
        "parameters": {"type": "object", "properties": {"holder": {"type": "string", "description": "Holder slug, e.g. 'garry' or 'people/charlie-example'. Defaults to 'garry' when omitted."}}, "required": []},
    },
    "gbrain_takes_list": {
        "name": "gbrain_takes_list",
        "mcp_name": "takes_list",
        "description": "List takes (typed/weighted/attributed claims) filtered by holder/kind/active/etc.",
        "parameters": {"type": "object", "properties": {"page_slug": {"type": "string", "description": "Filter to this page"}, "holder": {"type": "string", "description": "Filter to this holder (world|garry|brain|<slug>)"}, "kind": {"type": "string", "description": "Filter to this kind (fact|take|bet|hunch)"}, "active": {"type": "boolean", "description": "Active rows only (default true)"}, "resolved": {"type": "boolean", "description": "true \u2192 only resolved bets; false \u2192 only unresolved"}, "sort_by": {"type": "string", "description": "weight | since_date | created_at (default created_at)"}, "limit": {"type": "number", "description": "Max rows (default 100, cap 500)"}, "offset": {"type": "number", "description": "Skip first N rows"}}, "required": []},
    },
    "gbrain_takes_search": {
        "name": "gbrain_takes_search",
        "mcp_name": "takes_search",
        "description": "Keyword search across takes (pg_trgm similarity over claim text)",
        "parameters": {"type": "object", "properties": {"query": {"type": "string"}, "limit": {"type": "number", "description": "Max results (default 30, cap 100)"}}, "required": ["query"]},
    },
    "gbrain_think": {
        "name": "gbrain_think",
        "mcp_name": "think",
        "description": "Multi-hop synthesis across pages + takes + graph. Pulls relevant evidence and produces a cited answer with conflict + gap analysis.",
        "parameters": {"type": "object", "properties": {"question": {"type": "string", "description": "The question to think about"}, "anchor": {"type": "string", "description": "Pull the entity subgraph around this slug"}, "rounds": {"type": "number", "description": "Multi-pass: 1 (default). Round-loop scaffolding is in place; gap-driven retrieval ships in v0.29."}, "save": {"type": "boolean", "description": "Persist a synthesis page (local-CLI only; ignored for MCP)"}, "take": {"type": "boolean", "description": "Append a take row to the anchor page (requires anchor)"}, "model": {"type": "string", "description": "Model override (alias or full id). Falls through models.think \u2192 models.default \u2192 GBRAIN_MODEL \u2192 opus."}, "since": {"type": "string", "description": "Start of temporal window (YYYY-MM-DD or YYYY-MM)"}, "until": {"type": "string", "description": "End of temporal window"}}, "required": ["question"]},
    },
    "gbrain_takes_scorecard": {
        "name": "gbrain_takes_scorecard",
        "mcp_name": "takes_scorecard",
        "description": "Calibration scorecard for resolved bets: counts, accuracy, Brier (correct ∨ incorrect only), partial_rate.",
        "parameters": {"type": "object", "properties": {"holder": {"type": "string", "description": "Filter to this holder (world|garry|brain|<slug>)"}, "domain_prefix": {"type": "string", "description": "Slug prefix (e.g. companies/) to scope the scorecard"}, "since": {"type": "string", "description": "Window start (YYYY-MM-DD)"}, "until": {"type": "string", "description": "Window end (YYYY-MM-DD)"}}, "required": []},
    },
    "gbrain_takes_calibration": {
        "name": "gbrain_takes_calibration",
        "mcp_name": "takes_calibration",
        "description": "Calibration curve: resolved correct/incorrect bets binned by stated weight; observed vs predicted per bucket.",
        "parameters": {"type": "object", "properties": {"holder": {"type": "string", "description": "Filter to this holder"}, "bucket_size": {"type": "number", "description": "Bucket width in (0,1]; default 0.1"}}, "required": []},
    },
    "gbrain_whoami": {
        "name": "gbrain_whoami",
        "mcp_name": "whoami",
        "description": "Introspect the calling identity. Returns one of three transport shapes: {transport: \"oauth\", client_id, client_name, scopes, expires_at}, {transport: \"legacy\", token_name, scopes, expires_at: null}, or {transport: \"local\", scopes: []}. Throws unknown_transport when the context is ambiguous (remote=true without auth) — fail-closed posture mirroring the v0.26.9 trust-boundary contract.",
        "parameters": {"type": "object", "properties": {}, "required": []},
    },
    "gbrain_sources_add": {
        "name": "gbrain_sources_add",
        "mcp_name": "sources_add",
        "description": "Register a new source. Supports either --path (existing v0.17 behavior) or --url (v0.28 federated remote-clone path: parses the URL through the SSRF gate, clones into $GBRAIN_HOME/clones/<id>/ via temp-dir + rename atomicity, and stores remote_url in sources.config). Pre-flight collision check on id; rollback on either-side failure.",
        "parameters": {"type": "object", "properties": {"id": {"type": "string", "description": "Source id ([a-z0-9-]{1,32}). Immutable citation key."}, "name": {"type": "string", "description": "Display name (defaults to id)."}, "path": {"type": "string", "description": "Local path. Mutually optional with url."}, "url": {"type": "string", "description": "HTTPS git URL. Cloned into $GBRAIN_HOME/clones/<id>/. SSRF-guarded."}, "federated": {"type": "boolean", "description": "true \u2192 cross-source default search. false \u2192 isolated."}, "clone_dir": {"type": "string", "description": "Override clone destination (only valid with url). Default: $GBRAIN_HOME/clones/<id>/."}}, "required": ["id"]},
    },
    "gbrain_sources_list": {
        "name": "gbrain_sources_list",
        "mcp_name": "sources_list",
        "description": "List registered sources with page counts and remote_url. v0.28 surfaces the new remote_url field so a remote MCP caller can confirm a source is managed by clone+pull rather than user-supplied path.",
        "parameters": {"type": "object", "properties": {"include_archived": {"type": "boolean", "description": "Include soft-deleted sources."}}, "required": []},
    },
    "gbrain_sources_remove": {
        "name": "gbrain_sources_remove",
        "mcp_name": "sources_remove",
        "description": "Hard-remove a source (cascades pages/chunks/embeddings). Refuses to delete the auto-managed clone dir unless its resolved path is confined under $GBRAIN_HOME/clones/ (realpath+lstat — symlink-safe). For most workflows prefer sources_archive for the soft-delete path.",
        "parameters": {"type": "object", "properties": {"id": {"type": "string"}, "confirm_destructive": {"type": "boolean", "description": "Required when the source has data (pages, chunks). Without it the op refuses."}, "dry_run": {"type": "boolean", "description": "Preview impact without side effects."}, "keep_storage": {"type": "boolean", "description": "Skip clone-dir cleanup even when the source is auto-managed."}}, "required": ["id"]},
    },
    "gbrain_sources_status": {
        "name": "gbrain_sources_status",
        "mcp_name": "sources_status",
        "description": "Per-source diagnostic. Returns clone_state (\"healthy\" | \"missing\" | \"not-a-dir\" | \"no-git\" | \"url-drift\" | \"corrupted\" | \"not-applicable\") so a remote MCP caller can diagnose whether the on-disk clone is syncable without SSH access to the brain host.",
        "parameters": {"type": "object", "properties": {"id": {"type": "string"}}, "required": ["id"]},
    },
    "gbrain_get_recent_salience": {
        "name": "gbrain_get_recent_salience",
        "mcp_name": "get_recent_salience",
        "description": "Returns pages recently touched and ranked by emotional + activity salience (deterministic 0..1 emotional_weight + take density + recency decay). Use this when the user asks what's been going on, what's notable, what's hot, anything crazy happening, or for any open-ended 'current state' question about themselves or their work. Do NOT run a semantic search for these — salience surfaces what's unusual without needing a search term.",
        "parameters": {"type": "object", "properties": {"days": {"type": "number", "description": "Window in days. Default 14."}, "limit": {"type": "number", "description": "Max results (default 20, capped at 100)."}, "slugPrefix": {"type": "string", "description": "Optional slug-prefix filter, e.g. 'personal' or 'wiki/people'."}, "recency_bias": {"type": "string", "description": "v0.29.1: how to weight recency in the salience score.\n  'flat' (DEFAULT) \u2014 v0.29.0 behavior. Every page gets 1/(1+days_old).\n                     Stable, predictable; what most callers want.\n  'on'             \u2014 Per-prefix decay map. concepts/originals/writing/\n                     become evergreen (recency component = 0); daily/,\n                     media/x/, chat/ decay aggressively. Use when the\n                     user explicitly biases for recency-aware salience\n                     ('what's been salient lately' vs 'what matters\n                     in this brain regardless of when').", "enum": ["flat", "on"]}}, "required": []},
    },
    "gbrain_find_anomalies": {
        "name": "gbrain_find_anomalies",
        "mcp_name": "find_anomalies",
        "description": "Returns statistical anomalies in recent page activity, grouped by cohort (tag or type). Use this for questions about what stood out, what's unusual, or what changed recently. Returns explanatory cohorts (e.g. '15 pages tagged wedding touched on 2026-04-28, baseline 0.3/day') so you can speak about patterns the user wouldn't have searched for. Cohort kinds: tag, type. Year cohort is deferred to a later release.",
        "parameters": {"type": "object", "properties": {"since": {"type": "string", "description": "ISO date YYYY-MM-DD. Default = today (UTC)."}, "lookback_days": {"type": "number", "description": "Days of history for the baseline. Default 30."}, "sigma": {"type": "number", "description": "Sigma threshold. Default 3.0."}}, "required": []},
    },
    "gbrain_volunteer_context": {
        "name": "gbrain_volunteer_context",
        "mcp_name": "volunteer_context",
        "description": "Push-based context: volunteer brain pages relevant to a rolling conversation window WITHOUT being asked. Zero-LLM, confidence-gated (alias 0.9 / exact-title 0.8 / slug-suffix 0.6, +0.05 for multi-turn or newest-turn mentions; default gate 0.7), capped at 3 pages (max 5). Returns pointers with one-line rationales + synopses — open the page (get_page) before relying on details. Pass stats: true for the approximate volunteered-vs-used precision summary (the feedback loop).",
        "parameters": {"type": "object", "properties": {"window": {"type": "string", "description": "Recent conversation turns, oldest \u2192 newest, as 'user:' / 'assistant:' prefixed lines (unprefixed text = one user turn). Required unless stats: true. CLI: piped stdin fills this."}, "prior_context": {"type": "string", "description": "Already-surfaced context (pointer blocks / opened page bodies). Pages whose slug appears here are not re-volunteered."}, "max_pages": {"type": "number", "description": "Max pages to volunteer (default 3, hard cap 5)."}, "min_confidence": {"type": "number", "description": "Confidence gate 0..1 (default 0.7 \u2014 slug-suffix matches need an explicit lower gate)."}, "session_id": {"type": "string", "description": "Optional caller session id, logged for attribution."}, "turn": {"type": "number", "description": "Optional caller turn number, logged for attribution."}, "stats": {"type": "boolean", "description": "Return the volunteered-vs-used precision summary instead of volunteering. APPROXIMATE: \"used\" = pages.last_retrieved_at > volunteered_at."}, "days": {"type": "number", "description": "Stats window in days (default 30; stats mode only)."}}, "required": []},
    },
    "gbrain_extract_facts": {
        "name": "gbrain_extract_facts",
        "mcp_name": "extract_facts",
        "description": "v0.31: extract personal-knowledge facts (events, preferences, commitments, beliefs) from a conversation turn into the per-source hot memory. Sanitizes turn_text via INJECTION_PATTERNS, calls Haiku to extract structured claims, runs the cosine fast-path + classifier dedup pipeline, INSERTs into facts. Returns counts by status. Skips extraction when the turn is dream-generated content (anti-loop).",
        "parameters": {"type": "object", "properties": {"turn_text": {"type": "string", "description": "The user message or page body to extract facts from. Sanitized via INJECTION_PATTERNS before the LLM call."}, "session_id": {"type": "string", "description": "Opaque session id (e.g. topic-id from MCP _meta.session_id, or CLI --session). Stored on each fact for the recall --session filter. Not an auth surface."}, "entity_hints": {"type": "array", "description": "Existing canonical entity slugs the agent has already resolved. Helps the extractor pick the right slug.", "items": {"type": "string"}}, "is_dream_generated": {"type": "boolean", "description": "When true, extraction is skipped (anti-loop). Caller flips this on for pages with dream_generated:true frontmatter."}, "visibility": {"type": "string", "description": "Default visibility for extracted facts. private (default) | world."}}, "required": ["turn_text"]},
    },
    "gbrain_recall": {
        "name": "gbrain_recall",
        "mcp_name": "recall",
        "description": "v0.31: query per-source hot memory (facts table). Filters by entity / since / session. Remote callers see only visibility=world facts. Returns most-recent first. v0.32 adds optional include_pending to return pending_consolidation_count alongside facts in one round trip.",
        "parameters": {"type": "object", "properties": {"entity": {"type": "string", "description": "Entity slug (canonical). Returns facts about this entity newest first."}, "since": {"type": "string", "description": "ISO datetime or duration shorthand (e.g. \"8 hours ago\"). Returns facts created since."}, "session_id": {"type": "string", "description": "Source session id (e.g. topic-A). Returns facts captured in that session."}, "include_expired": {"type": "boolean", "description": "When true, include expired_at IS NOT NULL rows. Default false."}, "supersessions": {"type": "boolean", "description": "When true, return only the supersession audit log (expired_at + superseded_by both set)."}, "limit": {"type": "number", "description": "Max rows to return. Default 50, cap 100."}, "grep": {"type": "string", "description": "Substring filter on fact text (case-insensitive). Applied client-side after recall."}, "include_pending": {"type": "boolean", "description": "v0.32: when true, response includes pending_consolidation_count (facts not yet promoted to takes by the dream-cycle consolidate phase). One round trip; backward-compatible (field omitted when false)."}}, "required": []},
    },
    "gbrain_forget_fact": {
        "name": "gbrain_forget_fact",
        "mcp_name": "forget_fact",
        "description": "v0.32.2: forget a fact. Rewrites the page's `## Facts` fence to strike through the row and set valid_until=today (the DB's expired_at derives via valid_until + now() on the next reconcile so the forget survives `gbrain rebuild`). Falls back to legacy DB-only expire for pre-v51 / thin-client rows. Idempotent on already-expired or unknown ids.",
        "parameters": {"type": "object", "properties": {"id": {"type": "number", "description": "Fact id to forget."}, "reason": {"type": "string", "description": "Optional reason; written to the fence row's context cell as \"forgotten: <reason>\". Default: \"forgotten\"."}}, "required": ["id"]},
    },
    "gbrain_find_contradictions": {
        "name": "gbrain_find_contradictions",
        "mcp_name": "find_contradictions",
        "description": "v0.32.6 — return suspected-contradiction findings from the most recent `gbrain eval suspected-contradictions` probe run, optionally filtered by slug and/or severity. Use this when the user asks 'what's inconsistent in my brain', 'show me contradictions about Acme', 'high-severity issues only', or wants to act on the probe's findings without re-running it. Returns {contradictions: [{a, b, severity, axis, confidence, resolution_command}]}. Reads the cached run row — does NOT trigger a new probe; users run `gbrain eval suspected-contradictions` for that.",
        "parameters": {"type": "object", "properties": {"slug": {"type": "string", "description": "Optional slug filter; matches either side of a pair (substring match on slug)."}, "severity": {"type": "string", "description": "Optional severity filter.", "enum": ["low", "medium", "high"]}, "limit": {"type": "number", "description": "Max findings to return. Default 20."}}, "required": []},
    },
    "gbrain_find_experts": {
        "name": "gbrain_find_experts",
        "mcp_name": "find_experts",
        "description": "Answers 'who in my brain knows about <topic>'. Returns ranked person/company pages by expertise depth (sub-linear match score), relationship recency (exp decay with 6-month half-life), and salience. Use this for questions like 'who should I talk to about X', 'who knows about Y', 'find me someone who's worked on Z', or any expertise-routing intent. Filters at SQL to person + company pages — does NOT return notes or articles. Pair with --explain (CLI) to surface the per-result factor breakdown.",
        "parameters": {"type": "object", "properties": {"topic": {"type": "string", "description": "The topic to route. Free-form natural language."}, "limit": {"type": "number", "description": "Max results (default 5)."}, "explain": {"type": "boolean", "description": "Include factor breakdown per result (expertise, recency, salience)."}}, "required": []},
    },
    "gbrain_find_trajectory": {
        "name": "gbrain_find_trajectory",
        "mcp_name": "find_trajectory",
        "description": "v0.35.4 — return the chronological claim trajectory for an entity (typed metric values over time, plus auto-detected regressions and narrative drift). Use this when the user asks 'how has Acme's MRR trended', 'show me what alice-example said about runway over time', 'is this founder consistent', 'find regressions for fund-a's portfolio', or wants a time-series view of an entity's structured claims. Returns `{points: [{fact_id, valid_from, metric, value, unit, period, text, source_session, source_markdown_slug}], regressions: [{metric, from_value, from_date, to_value, to_date, delta_pct}], drift_score: number|null, schema_version: 1}`. Drift score 0 = stable narrative, 1 = every consecutive claim is unrelated; null when fewer than 3 typed points exist. Visibility-filtered for remote callers (world-only); source-scoped by the caller's OAuth source binding. Pair with `gbrain founder scorecard <slug>` for an aggregated rollup of the same data.",
        "parameters": {"type": "object", "properties": {"entity_slug": {"type": "string", "description": "Required. Entity slug to chart (e.g. \"companies/acme-example\", \"people/alice-example\")."}, "metric": {"type": "string", "description": "Optional. Filter to a single canonical metric (e.g. \"mrr\", \"arr\", \"team_size\"). When omitted, all metrics return."}, "kind": {"type": "string", "description": "Optional. Filter by row shape: \"metric\" (typed-claim rows only), \"event\" (event_type rows only), or \"all\" (default). v0.40.2.0+.", "enum": ["metric", "event", "all"]}, "since": {"type": "string", "description": "Optional lower bound on valid_from (YYYY-MM-DD or ISO)."}, "until": {"type": "string", "description": "Optional upper bound on valid_from (YYYY-MM-DD or ISO)."}, "limit": {"type": "number", "description": "Max points returned. Default 100, max 500."}}, "required": []},
    },
    "gbrain_code_callers": {
        "name": "gbrain_code_callers",
        "mcp_name": "code_callers",
        "description": "BEFORE editing any function, run code_callers with the symbol name to find every caller (the people who'd be affected by your change). Returns direct callers from the v0.20+ tree-sitter call graph. Use during plan-mode to size the change. Defaults to source-scoped; for multi-source brains pass source_id or all_sources=true. Returns: `{symbol, count, callers: [{from_symbol_qualified, to_symbol_qualified, edge_type, resolved}]}`. Example: `{symbol:'parseMarkdown', count:4, callers:[{from_symbol_qualified:'callerInA', to_symbol_qualified:'parseMarkdown', edge_type:'calls', resolved:true}]}`.",
        "parameters": {"type": "object", "properties": {"symbol": {"type": "string", "description": "Symbol to find callers of (bare or qualified name)."}, "limit": {"type": "number", "description": "Max edges returned. Default 100."}, "source_id": {"type": "string", "description": "Scope to a single source. Defaults to ctx.sourceId; '__all__' spans every source for trusted local callers, your granted sources for remote callers."}, "all_sources": {"type": "boolean", "description": "Span sources (equivalent to source_id=__all__): every source locally, your grant remotely."}}, "required": ["symbol"]},
    },
    "gbrain_code_callees": {
        "name": "gbrain_code_callees",
        "mcp_name": "code_callees",
        "description": "When tracing how a function flows to its dependencies (DB calls, HTTP calls, file I/O), run code_callees from the entry point. Forward view of the call graph: what does this symbol call? Use this when debugging unexpected behavior or when planning to extract / inline a function. Same shape as code_callers but the field is `callees` and the edge direction is reversed.",
        "parameters": {"type": "object", "properties": {"symbol": {"type": "string", "description": "Symbol to find callees of (bare or qualified name)."}, "limit": {"type": "number", "description": "Max edges returned. Default 100."}, "source_id": {"type": "string", "description": "Scope to a single source. Defaults to ctx.sourceId; '__all__' spans every source for trusted local callers, your granted sources for remote callers."}, "all_sources": {"type": "boolean", "description": "Span sources: every source locally, your grant remotely."}}, "required": ["symbol"]},
    },
    "gbrain_code_def": {
        "name": "gbrain_code_def",
        "mcp_name": "code_def",
        "description": "Where is this symbol defined? Returns one row per definition site (function, class, type, interface, enum, struct, trait, module, contract). Use this BEFORE reaching for grep when you want to read a definition. Single-result is the common case; multiple results indicate same-name symbols across files (which is information in itself). Returns: `{symbol, count, defs: [{slug, file, language, symbol_type, start_line, end_line, snippet}]}`. Filter by --lang to scope a polyglot brain (e.g., lang='typescript').",
        "parameters": {"type": "object", "properties": {"symbol": {"type": "string", "description": "Symbol name (bare token; e.g., parseMarkdown, BrainEngine)."}, "limit": {"type": "number", "description": "Max definition sites returned. Default 20."}, "lang": {"type": "string", "description": "Filter by content_chunks.language (e.g. 'typescript', 'python')."}}, "required": ["symbol"]},
    },
    "gbrain_code_refs": {
        "name": "gbrain_code_refs",
        "mcp_name": "code_refs",
        "description": "Find every reference to a symbol across the codebase (every file, every line). Differs from code_callers in two ways: (1) catches references in comments, strings, imports, type annotations — not just call sites; (2) returns line numbers, not symbol-qualified edges. Use this when planning a rename or deprecation where you need to touch every literal mention. Returns: `{symbol, count, refs: [{slug, file, language, line, context}]}`.",
        "parameters": {"type": "object", "properties": {"symbol": {"type": "string", "description": "Symbol to find references to."}, "limit": {"type": "number", "description": "Max references returned. Default 50."}, "lang": {"type": "string", "description": "Filter by content_chunks.language."}}, "required": ["symbol"]},
    },
    "gbrain_code_blast": {
        "name": "gbrain_code_blast",
        "mcp_name": "code_blast",
        "description": "BEFORE editing any function, run code_blast with the symbol name to surface every transitive caller grouped by depth (direct → 2-hop → 3-hop). Use this during plan-mode to size the change. Returns up to 200 nodes. Returns: {result, depth_groups?, truncation?, cycles_detected?, did_you_mean?, candidates?}. Example ok: {result:\"ok\", depth_groups:[{depth:1, nodes:[{symbol,chunk_id}], confidence:0.77}], truncation:\"none\"}.",
        "parameters": {"type": "object", "properties": {"symbol": {"type": "string", "description": "Bare or qualified symbol name (e.g. \"performSync\" or \"src/foo::performSync\")"}, "depth": {"type": "number", "description": "Hop cap (default 5, max 8)"}, "max_nodes": {"type": "number", "description": "Result-set cap (default 200)"}, "exact": {"type": "boolean", "description": "Skip bare-name disambiguation; treat symbol as exact qualified name"}, "source_id": {"type": "string", "description": "Source to traverse. Defaults to ctx.sourceId; federated clients with multiple granted sources must specify one."}}, "required": ["symbol"]},
    },
    "gbrain_code_flow": {
        "name": "gbrain_code_flow",
        "mcp_name": "code_flow",
        "description": "When tracing how a request flows through the codebase from entry point to side effect (DB write, HTTP call, file I/O), run code_flow from the entry point. Returns ordered execution chain with terminal-node tags. Returns: same envelope as code_blast plus terminal_nodes: [{symbol, sink_kind}] where sink_kind ∈ \"db_call\"|\"http_call\"|\"file_io\"|\"process_exec\"|\"unknown\".",
        "parameters": {"type": "object", "properties": {"entry_point": {"type": "string", "description": "Entry-point symbol name (bare or qualified)"}, "depth": {"type": "number", "description": "Hop cap (default 8, max 12)"}, "max_nodes": {"type": "number", "description": "Result-set cap (default 200)"}, "exact": {"type": "boolean", "description": "Skip bare-name disambiguation"}, "source_id": {"type": "string", "description": "Source to traverse. Defaults to ctx.sourceId; federated clients with multiple granted sources must specify one."}}, "required": ["entry_point"]},
    },
    "gbrain_get_active_schema_pack": {
        "name": "gbrain_get_active_schema_pack",
        "mcp_name": "get_active_schema_pack",
        "description": "v0.40.6.0: cheap identity packet for the active schema pack. Returns {pack_name, version, sha8, page_types_count, link_types_count, primitive_summary, source_tier}. Useful for agents to know which pack they are operating against without paying full manifest load cost.",
        "parameters": {"type": "object", "properties": {}, "required": []},
    },
    "gbrain_list_schema_packs": {
        "name": "gbrain_list_schema_packs",
        "mcp_name": "list_schema_packs",
        "description": "v0.40.6.0: list installed schema packs (bundled + user-installed). Returns {bundled: string[], installed: string[]}. Read-only directory listing.",
        "parameters": {"type": "object", "properties": {}, "required": []},
    },
    "gbrain_schema_stats": {
        "name": "gbrain_schema_stats",
        "mcp_name": "schema_stats",
        "description": "v0.40.6.0: per-type page counts + typed-coverage from the DB. Returns {schema_version:1, pack_identity, aggregate, per_source, dead_prefixes}. Multi-source aware via ctx.sourceId/allowedSources.",
        "parameters": {"type": "object", "properties": {}, "required": []},
    },
    "gbrain_schema_lint": {
        "name": "gbrain_schema_lint",
        "mcp_name": "schema_lint",
        "description": "v0.40.6.0: lint the active (or named) schema pack. File-plane rules only over MCP — the with_db option is rejected for remote callers (DB-aware rules require local CLI). Returns {ok, errors, warnings} structured report.",
        "parameters": {"type": "object", "properties": {"pack": {"type": "string", "description": "Pack name (default: active pack)"}}, "required": []},
    },
    "gbrain_schema_graph": {
        "name": "gbrain_schema_graph",
        "mcp_name": "schema_graph",
        "description": "v0.40.6.0: schema pack graph as JSON edges. Returns {nodes: [{name, primitive}], edges: [{from, verb, to}]} derived from link_types inference + frontmatter_links.",
        "parameters": {"type": "object", "properties": {}, "required": []},
    },
    "gbrain_schema_explain_type": {
        "name": "gbrain_schema_explain_type",
        "mcp_name": "schema_explain_type",
        "description": "v0.40.6.0: resolved settings for a single page_type in the active pack. Returns {pack, type, primitive, path_prefixes, aliases, extractable, expert_routing}.",
        "parameters": {"type": "object", "properties": {"type": {"type": "string", "description": "Page type name to explain"}}, "required": ["type"]},
    },
    "gbrain_schema_review_orphans": {
        "name": "gbrain_schema_review_orphans",
        "mcp_name": "schema_review_orphans",
        "description": "v0.40.6.0: list pages with no active-pack type match. Returns {orphan_count, orphans: [{slug, source_id}]}.",
        "parameters": {"type": "object", "properties": {"limit": {"type": "number", "description": "Max orphans to return (default 100)"}}, "required": []},
    },
    "gbrain_schema_apply_mutations": {
        "name": "gbrain_schema_apply_mutations",
        "mcp_name": "schema_apply_mutations",
        "description": "v0.40.7.0: batched schema pack mutation. ATOMIC: all mutations succeed or all roll back. Audit log records one batch_id. Admin scope; NOT localOnly so remote agents (your OpenClaw, etc.) can author packs over normal MCP. Mutation shape per ApplyMutationsRequest type — supports add_type / remove_type / update_type / add_alias / remove_alias / add_prefix / remove_prefix / add_link_type / remove_link_type / set_extractable / set_expert_routing.",
        "parameters": {"type": "object", "properties": {"pack": {"type": "string", "description": "Pack to mutate (must not be bundled)"}, "mutations": {"type": "array", "description": "Array of {op, ...args} mutation records to apply atomically", "items": {"type": "object"}}, "force": {"type": "boolean", "description": "Steal stale per-pack lock"}}, "required": ["pack", "mutations"]},
    },
    "gbrain_reload_schema_pack": {
        "name": "gbrain_reload_schema_pack",
        "mcp_name": "reload_schema_pack",
        "description": "v0.40.6.0: flush the in-process schema pack cache so the next loadActivePack re-reads from disk. Cascades through extends-chain (codex C6). Admin scope; NOT localOnly. Returns {invalidated: string[]}.",
        "parameters": {"type": "object", "properties": {"pack": {"type": "string", "description": "Pack name to invalidate (omit to flush all)"}}, "required": []},
    },
    "gbrain_run_onboard": {
        "name": "gbrain_run_onboard",
        "mcp_name": "run_onboard",
        "description": "Probe brain health + optionally submit onboard remediations. Admin scope required. Protected handlers (LLM-bearing) require run_protected_onboard scope ADDITIONALLY.",
        "parameters": {"type": "object", "properties": {"mode": {"type": "string", "description": "'check' (default), 'auto', or 'auto-with-prompt'"}, "target_score": {"type": "number", "description": "Target brain_score (default 90)"}, "max_usd": {"type": "number", "description": "USD cap for autopilot path (required for auto modes)"}}, "required": []},
    },
    "gbrain_run_skillopt": {
        "name": "gbrain_run_skillopt",
        "mcp_name": "run_skillopt",
        "description": "Run SkillOpt against a single skill. Admin scope; mutating; rate-limited per-skill via DB lock. See gbrain skillopt CLI for the full flag surface.",
        "parameters": {"type": "object", "properties": {"skill_name": {"type": "string", "description": "Kebab-case skill name (resolves to skills/<name>/SKILL.md)"}, "benchmark_path": {"type": "string", "description": "Absolute path to benchmark JSONL; defaults to skills/<name>/skillopt-benchmark.jsonl"}, "epochs": {"type": "number", "description": "Default 4"}, "batch_size": {"type": "number", "description": "Default 8"}, "lr": {"type": "number", "description": "Default 4"}, "max_cost_usd": {"type": "number", "description": "Default 5.00"}, "no_mutate": {"type": "boolean", "description": "Write proposed.md without replacing SKILL.md"}, "allow_mutate_bundled": {"type": "boolean", "description": "Required to mutate bundled skills"}, "held_out_path": {"type": "string", "description": "Path to a held-out test set (JSONL). REQUIRED (>=5 rows) to mutate a bundled skill in place \u2014 otherwise the run hard-refuses. Remote callers: must resolve within the skills directory."}, "dry_run": {"type": "boolean", "description": "Cost preview, no LLM calls"}}, "required": ["skill_name"]},
    },
}

HARDCODED_SCHEMA_DICTS = [
    HARDCODED_SCHEMAS["gbrain_get_page"],
    HARDCODED_SCHEMAS["gbrain_put_page"],
    HARDCODED_SCHEMAS["gbrain_delete_page"],
    HARDCODED_SCHEMAS["gbrain_list_pages"],
    HARDCODED_SCHEMAS["gbrain_restore_page"],
    HARDCODED_SCHEMAS["gbrain_search"],
    HARDCODED_SCHEMAS["gbrain_query"],
    HARDCODED_SCHEMAS["gbrain_search_by_image"],
    HARDCODED_SCHEMAS["gbrain_add_tag"],
    HARDCODED_SCHEMAS["gbrain_remove_tag"],
    HARDCODED_SCHEMAS["gbrain_get_tags"],
    HARDCODED_SCHEMAS["gbrain_add_link"],
    HARDCODED_SCHEMAS["gbrain_remove_link"],
    HARDCODED_SCHEMAS["gbrain_get_links"],
    HARDCODED_SCHEMAS["gbrain_get_backlinks"],
    HARDCODED_SCHEMAS["gbrain_list_link_sources"],
    HARDCODED_SCHEMAS["gbrain_traverse_graph"],
    HARDCODED_SCHEMAS["gbrain_add_timeline_entry"],
    HARDCODED_SCHEMAS["gbrain_get_timeline"],
    HARDCODED_SCHEMAS["gbrain_get_stats"],
    HARDCODED_SCHEMAS["gbrain_get_health"],
    HARDCODED_SCHEMAS["gbrain_run_doctor"],
    HARDCODED_SCHEMAS["gbrain_get_versions"],
    HARDCODED_SCHEMAS["gbrain_revert_version"],
    HARDCODED_SCHEMAS["gbrain_get_brain_identity"],
    HARDCODED_SCHEMAS["gbrain_list_skills"],
    HARDCODED_SCHEMAS["gbrain_get_skill"],
    HARDCODED_SCHEMAS["gbrain_get_status_snapshot"],
    HARDCODED_SCHEMAS["gbrain_put_raw_data"],
    HARDCODED_SCHEMAS["gbrain_get_raw_data"],
    HARDCODED_SCHEMAS["gbrain_resolve_slugs"],
    HARDCODED_SCHEMAS["gbrain_get_chunks"],
    HARDCODED_SCHEMAS["gbrain_log_ingest"],
    HARDCODED_SCHEMAS["gbrain_get_ingest_log"],
    HARDCODED_SCHEMAS["gbrain_submit_job"],
    HARDCODED_SCHEMAS["gbrain_get_job"],
    HARDCODED_SCHEMAS["gbrain_list_jobs"],
    HARDCODED_SCHEMAS["gbrain_cancel_job"],
    HARDCODED_SCHEMAS["gbrain_retry_job"],
    HARDCODED_SCHEMAS["gbrain_get_job_progress"],
    HARDCODED_SCHEMAS["gbrain_pause_job"],
    HARDCODED_SCHEMAS["gbrain_resume_job"],
    HARDCODED_SCHEMAS["gbrain_replay_job"],
    HARDCODED_SCHEMAS["gbrain_send_job_message"],
    HARDCODED_SCHEMAS["gbrain_submit_agent"],
    HARDCODED_SCHEMAS["gbrain_find_orphans"],
    HARDCODED_SCHEMAS["gbrain_get_calibration_profile"],
    HARDCODED_SCHEMAS["gbrain_takes_list"],
    HARDCODED_SCHEMAS["gbrain_takes_search"],
    HARDCODED_SCHEMAS["gbrain_think"],
    HARDCODED_SCHEMAS["gbrain_takes_scorecard"],
    HARDCODED_SCHEMAS["gbrain_takes_calibration"],
    HARDCODED_SCHEMAS["gbrain_whoami"],
    HARDCODED_SCHEMAS["gbrain_sources_add"],
    HARDCODED_SCHEMAS["gbrain_sources_list"],
    HARDCODED_SCHEMAS["gbrain_sources_remove"],
    HARDCODED_SCHEMAS["gbrain_sources_status"],
    HARDCODED_SCHEMAS["gbrain_get_recent_salience"],
    HARDCODED_SCHEMAS["gbrain_find_anomalies"],
    HARDCODED_SCHEMAS["gbrain_volunteer_context"],
    HARDCODED_SCHEMAS["gbrain_extract_facts"],
    HARDCODED_SCHEMAS["gbrain_recall"],
    HARDCODED_SCHEMAS["gbrain_forget_fact"],
    HARDCODED_SCHEMAS["gbrain_find_contradictions"],
    HARDCODED_SCHEMAS["gbrain_find_experts"],
    HARDCODED_SCHEMAS["gbrain_find_trajectory"],
    HARDCODED_SCHEMAS["gbrain_code_callers"],
    HARDCODED_SCHEMAS["gbrain_code_callees"],
    HARDCODED_SCHEMAS["gbrain_code_def"],
    HARDCODED_SCHEMAS["gbrain_code_refs"],
    HARDCODED_SCHEMAS["gbrain_code_blast"],
    HARDCODED_SCHEMAS["gbrain_code_flow"],
    HARDCODED_SCHEMAS["gbrain_get_active_schema_pack"],
    HARDCODED_SCHEMAS["gbrain_list_schema_packs"],
    HARDCODED_SCHEMAS["gbrain_schema_stats"],
    HARDCODED_SCHEMAS["gbrain_schema_lint"],
    HARDCODED_SCHEMAS["gbrain_schema_graph"],
    HARDCODED_SCHEMAS["gbrain_schema_explain_type"],
    HARDCODED_SCHEMAS["gbrain_schema_review_orphans"],
    HARDCODED_SCHEMAS["gbrain_schema_apply_mutations"],
    HARDCODED_SCHEMAS["gbrain_reload_schema_pack"],
    HARDCODED_SCHEMAS["gbrain_run_onboard"],
    HARDCODED_SCHEMAS["gbrain_run_skillopt"],
]
